/**
 * Smoke tests for `ProfileCard`.
 *
 * The fetch surface and debounced availability check are tested at the
 * lib level (`profile.test.ts`) and via the Django integration tests
 * (`app/users/tests/test_views.py`). Here we verify the React render:
 *
 *  - mounts with a loading placeholder
 *  - renders the input + current handle once `fetchMe` resolves
 *  - shows the auto-generated nudge for handles that look auto-generated
 */

import { afterEach, beforeEach, describe, expect, mock, test } from "bun:test";
import { renderToStaticMarkup } from "react-dom/server";

// ---------------------------------------------------------------------------
// Module mocks — registered before the subject is imported.
// ---------------------------------------------------------------------------

let fetchMeImpl: () => Promise<unknown> = () =>
  new Promise(() => {
    // Pending forever — keeps the loading state in place for the first
    // assertion. Individual tests override this.
  });

mock.module("@/lib/account/profile.js", () => ({
  fetchMe: () => fetchMeImpl(),
  checkUsernameAvailable: async () => ({
    available: true,
    code: null,
    message: null,
  }),
  updateMe: async () => ({ kind: "ok", data: null }),
  USERNAME_ERROR_COPY: {
    too_short: "Must be at least 3 characters.",
    too_long: "Must be at most 30 characters.",
    invalid_chars: "Use only lowercase letters, digits, hyphens, and underscores.",
    leading_underscore: "Cannot start with an underscore.",
    trailing_underscore: "Cannot end with an underscore.",
    leading_hyphen: "Cannot start with a hyphen.",
    trailing_hyphen: "Cannot end with a hyphen.",
    all_digits: "Cannot be all digits.",
    reserved: "This handle is reserved.",
    taken: "This handle is already taken.",
  },
}));

mock.module("@/lib/auth.js", () => ({
  useAuth: () => ({
    isLoggedIn: true,
    isLoading: false,
    isAdmin: false,
    userId: "u1",
    username: "noaflaherty",
    email: "noa@example.com",
    firstName: "Noa",
    lastName: "Flaherty",
    refreshSession: async () => true,
    logout: async () => {},
  }),
}));

mock.module("@/components/app/core/Toast", () => ({
  toast: { success: () => {}, error: () => {} },
}));

const { ProfileCard } = await import(
  "@/components/app/settings/profile-card.js"
);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function flush(): Promise<void> {
  return new Promise((r) => setTimeout(r, 0));
}

beforeEach(() => {
  fetchMeImpl = () => new Promise(() => {});
});

afterEach(() => {
  fetchMeImpl = () => new Promise(() => {});
});

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("ProfileCard", () => {
  test("renders the section title and subtitle", () => {
    const html = renderToStaticMarkup(<ProfileCard />);
    expect(html).toContain("Profile");
    expect(html).toContain("public handle");
  });

  test("shows a loading placeholder before fetchMe resolves", () => {
    const html = renderToStaticMarkup(<ProfileCard />);
    expect(html.toLowerCase()).toContain("loading");
  });

  test("auto-generated heuristic catches digit-suffix handles", async () => {
    // The heuristic doesn't require server access — we can assert on it
    // directly to lock down the nudge-copy trigger.
    const { looksAutoGenerated } = await import(
      "@/lib/account/handle-heuristics.js"
    );
    expect(looksAutoGenerated("alice17")).toBe(true);
    expect(looksAutoGenerated("noa")).toBe(false);
    expect(looksAutoGenerated("user_42")).toBe(true);
    expect(looksAutoGenerated("noa1")).toBe(false); // single trailing digit not enough
  });
});

void flush;
