/**
 * Numeric parity between the TypeScript fbank front end and the Python
 * reference (`torchaudio.compliance.kaldi.fbank`) that produced the
 * features ECAPA-TDNN was trained on.
 *
 * This test is the reason the front end can be trusted. A wrong feature
 * pipeline does not throw and does not look broken: it yields embeddings
 * that still cluster, just measurably worse. During the spike, feeding
 * int16-scale audio instead of normalized audio cost 0.08 of cosine
 * fidelity and nearly 40% of the same/different speaker separation,
 * with no error anywhere. Only a numeric diff catches that class of bug.
 *
 * Golden vectors are regenerated by `fixtures/make-fixtures.py`.
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, test } from "bun:test";

import {
  applyCmn,
  computeFbank,
  frameCount,
  WESPEAKER_FBANK,
} from "../fbank.js";
import { decodeWav } from "../wav.js";

const FIXTURES = join(import.meta.dir, "fixtures");

interface ParityMeta {
  sampleRate: number;
  samples: number;
  frames: number;
  melBins: number;
}

function loadFloat32(name: string): Float32Array {
  const buf = readFileSync(join(FIXTURES, name));
  return new Float32Array(buf.buffer, buf.byteOffset, buf.byteLength / 4);
}

const meta = JSON.parse(
  readFileSync(join(FIXTURES, "parity-meta.json"), "utf8"),
) as ParityMeta;
const clip = readFileSync(join(FIXTURES, "parity-clip.wav"));
const audio = decodeWav(
  clip.buffer.slice(clip.byteOffset, clip.byteOffset + clip.byteLength),
);

/** Largest absolute difference, and where it is. */
function maxAbsDiff(
  a: Float32Array,
  b: Float32Array,
): { max: number; at: number } {
  let max = 0;
  let at = -1;
  for (let i = 0; i < a.length; i++) {
    const d = Math.abs(a[i]! - b[i]!);
    if (d > max) {
      max = d;
      at = i;
    }
  }
  return { max, at };
}

describe("wav decoding", () => {
  test("decodes the fixture to the sample rate and length Python saw", () => {
    expect(audio.sampleRate).toBe(meta.sampleRate);
    expect(audio.samples.length).toBe(meta.samples);
  });

  test("rejects a non-WAV buffer rather than guessing", () => {
    expect(() => decodeWav(new Uint8Array([1, 2, 3, 4]).buffer)).toThrow();
  });
});

describe("fbank parity with torchaudio kaldi", () => {
  test("produces the same frame count", () => {
    expect(frameCount(audio.samples.length)).toBe(meta.frames);
  });

  test("raw log-mel features match the Python reference", () => {
    const golden = loadFloat32("parity-fbank-raw.f32");
    const got = computeFbank(audio.samples);

    expect(got.frames).toBe(meta.frames);
    expect(got.dim).toBe(meta.melBins);
    expect(got.data.length).toBe(golden.length);

    // float32 (torch) against float64 (JS) accumulation, so exact
    // equality is not available. This bound is far tighter than any
    // real pipeline error, which shows up at 1e-1 or worse.
    const { max, at } = maxAbsDiff(got.data, golden);
    expect(max).toBeLessThan(1e-3);
    expect(at === -1 || Number.isFinite(max)).toBe(true);
  });

  test("CMN features match the Python reference", () => {
    const golden = loadFloat32("parity-fbank-cmn.f32");
    const got = applyCmn(computeFbank(audio.samples));
    const { max } = maxAbsDiff(got.data, golden);
    expect(max).toBeLessThan(1e-3);
  });

  test("CMN centers every coefficient on zero", () => {
    const got = applyCmn(computeFbank(audio.samples));
    for (let d = 0; d < got.dim; d++) {
      let sum = 0;
      for (let f = 0; f < got.frames; f++) {
        sum += got.data[f * got.dim + d]!;
      }
      expect(Math.abs(sum / got.frames)).toBeLessThan(1e-4);
    }
  });

  test("is gain-invariant in every mel bin that stays off the energy floor", () => {
    // Scaling the waveform by k scales every mel energy by k^2, which is a
    // constant offset in the log domain and so is removed by CMN. That
    // holds only while energies stay above the float32 floor Kaldi clamps
    // to. A single floored frame changes that bin's column mean, and CMN
    // then spreads the shift across every frame of the column, so a bin
    // with any floored frame moves as a whole. Assert the invariance where
    // it genuinely holds rather than pretending it is global.
    const quieter = new Float32Array(audio.samples.length);
    for (let i = 0; i < quieter.length; i++) {
      quieter[i] = audio.samples[i]! * 0.5;
    }

    const floorValue = Math.log(1.1920928955078125e-7);
    const rawLoud = computeFbank(audio.samples);
    const rawQuiet = computeFbank(quieter);
    const floored = new Set<number>();
    for (let i = 0; i < rawLoud.data.length; i++) {
      if (
        Math.abs(rawLoud.data[i]! - floorValue) < 1e-6 ||
        Math.abs(rawQuiet.data[i]! - floorValue) < 1e-6
      ) {
        floored.add(i % rawLoud.dim);
      }
    }

    const a = applyCmn(computeFbank(audio.samples));
    const b = applyCmn(computeFbank(quieter));
    let compared = 0;
    for (let f = 0; f < a.frames; f++) {
      for (let d = 0; d < a.dim; d++) {
        if (floored.has(d)) {
          continue;
        }
        const i = f * a.dim + d;
        expect(Math.abs(a.data[i]! - b.data[i]!)).toBeLessThan(1e-3);
        compared++;
      }
    }
    // Guard against the exclusion swallowing the whole test.
    expect(compared).toBeGreaterThan(a.data.length / 2);
  });

  test("returns no frames for a signal shorter than one window", () => {
    const tiny = new Float32Array(WESPEAKER_FBANK.sampleRate * 0.01);
    const got = computeFbank(tiny);
    expect(got.frames).toBe(0);
    expect(got.data.length).toBe(0);
  });
});
