#!/usr/bin/env bun
/**
 * Copies canonical repo files into locations where bundled/compiled builds can
 * resolve them without the repo-root meta/ or plugins/ trees:
 *   - feature-flag-registry.json → assistant/, gateway/, web/
 *   - plugins/marketplace.json    → the assistant plugin catalog (offline reader)
 *
 * Usage:
 *   bun run meta/sync-bundled-copies.ts          # write copies
 *   bun run meta/sync-bundled-copies.ts --check  # fail on drift
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const ROOT = resolve(import.meta.dir);

const PAIRS: { canonical: string; targets: string[] }[] = [
  {
    canonical: join(ROOT, "feature-flags", "feature-flag-registry.json"),
    targets: [
      join(ROOT, "..", "assistant", "src", "config", "feature-flag-registry.json"),
      join(ROOT, "..", "gateway", "src", "feature-flag-registry.json"),
      join(ROOT, "..", "clients", "web", "src", "lib", "feature-flags", "feature-flag-registry.json"),
    ],
  },
  {
    canonical: join(ROOT, "..", "plugins", "marketplace.json"),
    targets: [
      join(ROOT, "..", "assistant", "src", "cli", "lib", "bundled-marketplace.json"),
    ],
  },
];

const CHECK = process.argv.includes("--check");

// Some targets are gitignored build artifacts (regenerated by CI's sync step),
// not committed files. Only committed copies can go stale in the repo, so the
// drift guard skips anything git ignores — keeping .gitignore the SoT.
const isGitIgnored = (target: string): boolean => {
  try {
    execFileSync("git", ["check-ignore", "--quiet", target], { stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
};

let count = 0;
const drifted: string[] = [];
for (const { canonical, targets } of PAIRS) {
  const expected = readFileSync(canonical);
  for (const target of targets) {
    if (CHECK) {
      if (isGitIgnored(target)) continue;
      let actual: Buffer | null = null;
      try {
        actual = readFileSync(target);
      } catch {
        actual = null;
      }
      if (actual === null || !actual.equals(expected)) {
        drifted.push(target);
      }
      count++;
    } else {
      writeFileSync(target, expected);
      count++;
    }
  }
}

if (CHECK) {
  if (drifted.length > 0) {
    console.error(
      "✗ Bundled copies are out of sync with their canonical sources. " +
        "Run `bun run meta/sync-bundled-copies.ts` and commit:",
    );
    for (const target of drifted) console.error(`  - ${target}`);
    process.exit(1);
  }
  console.log(`✓ All ${count} committed bundled copies match their canonical sources`);
} else {
  console.log(
    `✓ Synced feature-flag-registry.json and plugins/marketplace.json to ${count} targets`,
  );
}
