username: Build Alerts

pretext: >-
  {{icon jobStatus}} {{jobName}} {{jobStatus}}
  {{#if (and env.SHOULD_TAG (eq env.SHOULD_TAG 'true'))}}by <@{{ env.SLACK_USER_ID }}>{{else}}by {{ env.SLACK_USER_ID }}{{/if}}
  <{{repositoryUrl}}|{{repositoryName}}>

text: |
  *<{{workflowRunUrl}}|{{workflow}}>*

fallback: |-
  [{{repositoryName}}] {{jobName}} - {{jobStatus}}

footer: >-
  <{{repositoryUrl}}|{{repositoryName}}> {{workflow}} #{{runNumber}}

colors:
  success: "#5DADE2"
  failure: "#884EA0"
  cancelled: "#A569BD"
  default: "#7D3C98"

icons:
  success: ":white_check_mark:"
  failure: ":kimk-cryingggggggg:"
  cancelled: ":meow_meltshoe:"
  skipped: ":dw_arthur_side_eye:"
  default: ":interrobang:"
