#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PACKAGE_DIR="$ROOT_DIR/native/mac-helper"
OUTPUT_DIR="$ROOT_DIR/resources"
# $OUTPUT_BUNDLE (the .app folder) is set after the env block below. macOS
# System Settings → Privacy & Security renders the .app folder name — not
# CFBundleName/CFBundleDisplayName, and not the executable filename — when
# listing this helper's grants, so the folder is named per-environment.
# CFBundleExecutable must still match the on-disk filename or codesign
# rejects the bundle.
TEMPLATE_PLIST="$PACKAGE_DIR/Sources/MacHelperExecutable/Info.plist"

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "build-mac-helper: skipping non-macOS host"
  exit 0
fi

if ! command -v xcrun >/dev/null 2>&1; then
  echo "build-mac-helper: xcrun not found; install Xcode command line tools" >&2
  exit 1
fi

BUILD_ARGS=(--package-path "$PACKAGE_DIR" -c release)
if [ -n "${ELECTRON_TARGET_ARCH:-}" ]; then
  case "$ELECTRON_TARGET_ARCH" in
    arm64) BUILD_ARGS+=(--triple arm64-apple-macosx15.0) ;;
    x64)   BUILD_ARGS+=(--triple x86_64-apple-macosx15.0) ;;
  esac
fi

# Per-environment helper identity so side-by-side installs (e.g. Vellum +
# Vellum Dev) get distinct TCC entries instead of colliding on one shared
# bundle id. Mirrors the app's appId/productName scheme in
# electron-builder.config.cjs; production keeps the bare id + name so existing
# grants persist.
ENV="${VELLUM_ENVIRONMENT:-local}"
if [ "$ENV" = "production" ]; then
  HELPER_BUNDLE_ID="ai.vellum.assistant.mac-helper"
  HELPER_DISPLAY_NAME="Vellum Helper"
else
  ENV_CAP="$(printf '%s' "${ENV:0:1}" | tr '[:lower:]' '[:upper:]')${ENV:1}"
  HELPER_BUNDLE_ID="ai.vellum.assistant-${ENV}.mac-helper"
  HELPER_DISPLAY_NAME="Vellum Helper ${ENV_CAP}"
fi

# Name the .app folder AND the executable per environment. The helper is
# spawned directly (execve, not via LaunchServices); the Privacy & Security
# list shows the .app folder name, not CFBundleName/CFBundleDisplayName or
# the executable filename. Naming both the folder and the binary after the
# env display name ("Vellum Helper", "Vellum Helper Dev", …) is what makes
# the Settings entry read correctly.
HELPER_BUNDLE_NAME="$HELPER_DISPLAY_NAME"
HELPER_EXEC_NAME="$HELPER_DISPLAY_NAME"
OUTPUT_BUNDLE="$OUTPUT_DIR/$HELPER_BUNDLE_NAME.app"
OUTPUT="$OUTPUT_BUNDLE/Contents/MacOS/$HELPER_EXEC_NAME"
OUTPUT_INFO_PLIST="$OUTPUT_BUNDLE/Contents/Info.plist"
# Sidecar so the runtime can resolve the .app folder without hardcoding the
# env→name mapping in TS. electron-builder copies this alongside the bundle
# into Vellum.app/Contents/Resources/bin/. macOS Finder hides it, but the
# runtime doesn't care.
HELPER_BUNDLE_NAME_SIDECAR="$OUTPUT_DIR/.vellum-mac-helper.bundle-name"

mkdir -p "$OUTPUT_DIR"
# Render the templated Info.plist, then embed it into the bare executable's
# __info_plist section so TCC can attribute permission prompts for the
# dictation-partials session without a full .app bundle. Content-address the
# filename: llbuild ignores content changes to a fixed -sectcreate input path
# and would skip relinking on an env switch, embedding a stale plist — a new
# identity must yield a new path to force the relink.
rm -f "$OUTPUT_DIR"/.vellum-mac-helper.*.Info.plist
RENDERED_TMP="$(mktemp)"
sed -e "s|__HELPER_BUNDLE_ID__|${HELPER_BUNDLE_ID}|g" \
    -e "s|__HELPER_DISPLAY_NAME__|${HELPER_DISPLAY_NAME}|g" \
    -e "s|__HELPER_EXEC_NAME__|${HELPER_EXEC_NAME}|g" \
    "$TEMPLATE_PLIST" > "$RENDERED_TMP"
RENDERED_PLIST="$OUTPUT_DIR/.vellum-mac-helper.$(shasum -a 256 "$RENDERED_TMP" | cut -c1-16).Info.plist"
mv -f "$RENDERED_TMP" "$RENDERED_PLIST"
BUILD_ARGS+=(
  -Xlinker -sectcreate
  -Xlinker __TEXT
  -Xlinker __info_plist
  -Xlinker "$RENDERED_PLIST"
)

# Clear any bare binary / `vellum-mac-helper.app` outputs so a rebuild never
# leaves an orphan bundle on disk next to the per-env one; the corresponding
# TCC row in Settings persists until manually toggled off (or
# `tccutil reset Accessibility ai.vellum.assistant.mac-helper`).
rm -f "$OUTPUT_DIR/hotkey-helper" "$OUTPUT_DIR/vellum-mac-helper" "$OUTPUT_DIR/Info.plist"
rm -rf "$OUTPUT_DIR/vellum-mac-helper.app"
xcrun swift build "${BUILD_ARGS[@]}"
BUILD_DIR="$(xcrun swift build "${BUILD_ARGS[@]}" --show-bin-path)"

# Vellum app icon (CFBundleIconFile) so the helper reads as part of Vellum in
# Privacy & Security. Generated by generate-icon.sh, which pack.sh runs first;
# absent during plain postinstall, so its presence is optional.
ICON_SRC="$ROOT_DIR/build/icon.icns"

# Skip the install when the build output is unchanged: replacing and
# re-signing churns nothing semantically, but a fresh bundle invalidates
# the CDHash that TCC keys the helper's mic/speech grants on, so every
# no-op rebuild (e.g. `bun run dev`'s postinstall) would re-prompt. The
# signed binary never byte-matches the unsigned build output, so compare
# against a hash marker of the inputs recorded at install time.
HASH_INPUTS=("$BUILD_DIR/vellum-mac-helper" "$RENDERED_PLIST" "$ROOT_DIR/scripts/entitlements/helper.plist")
[ -f "$ICON_SRC" ] && HASH_INPUTS+=("$ICON_SRC")
SOURCE_HASH="$(cat "${HASH_INPUTS[@]}" | shasum -a 256 | cut -d' ' -f1)"
HASH_MARKER="$OUTPUT_DIR/.vellum-mac-helper.source-hash"
if [ -x "$OUTPUT" ] && [ -f "$HASH_MARKER" ] && [ "$(cat "$HASH_MARKER")" = "$SOURCE_HASH" ]; then
  echo "build-mac-helper: bundle unchanged; keeping existing copy"
else
  # Remove before installing: overwriting a signed Mach-O in place reuses
  # the inode, and the kernel's stale signature cache SIGKILLs the next
  # spawn (exit 137). A fresh bundle sidesteps it.
  rm -rf "$OUTPUT_BUNDLE"
  mkdir -p "$OUTPUT_BUNDLE/Contents/MacOS"
  cp "$BUILD_DIR/vellum-mac-helper" "$OUTPUT"
  cp "$RENDERED_PLIST" "$OUTPUT_INFO_PLIST"
  chmod 755 "$OUTPUT"
  if [ -f "$ICON_SRC" ]; then
    mkdir -p "$OUTPUT_BUNDLE/Contents/Resources"
    cp "$ICON_SRC" "$OUTPUT_BUNDLE/Contents/Resources/AppIcon.icns"
  fi
  codesign --force --sign - --entitlements "$ROOT_DIR/scripts/entitlements/helper.plist" "$OUTPUT_BUNDLE"
  printf '%s' "$SOURCE_HASH" > "$HASH_MARKER"
fi

# Always rewrite the sidecar so it tracks the current build's bundle name —
# the runtime reads it instead of hardcoding the env→name mapping. Write
# unconditionally (cheap) rather than only on rebuild, so a no-op rebuild
# that keeps the existing bundle still has a sidecar pointing at it.
printf '%s' "$HELPER_BUNDLE_NAME" > "$HELPER_BUNDLE_NAME_SIDECAR"
