export {
  INITIAL_TERMINAL_STATE,
  terminalReducer,
  useTerminalState,
  type ConnectFailed,
  type ConnectRequested,
  type ConnectSucceeded,
  type Disconnected,
  type ErrorOccurred,
  type ReconnectFailed,
  type ReconnectRequested,
  type ReconnectSucceeded,
  type TerminalClosed,
  type TerminalEvent,
  type TerminalReset,
  type TerminalState,
  type TerminalStatus,
} from "@/domains/terminal/use-terminal-state.js";
