import SwiftUI
import VellumAssistantShared

/// Unified display item for both local and shared apps.
private struct DisplayAppItem: Identifiable {
    let id: String
    let name: String
    let description: String?
    let icon: String?
    let dateLabel: String
    let isShared: Bool
    let trustTier: String?
    let signerDisplayName: String?

    /// For local apps: the app store ID used for bundling.
    let localAppId: String?
    /// For shared apps: the UUID used for deletion and re-sharing.
    let sharedUUID: String?
}

struct GeneratedPanel: View {
    var onClose: () -> Void
    @Binding var isExpanded: Bool
    let daemonClient: DaemonClient
    /// When set, app opens route to the workspace instead of a floating NSPanel.
    var onOpenApp: ((UiSurfaceShowMessage) -> Void)?

    @State private var displayItems: [DisplayAppItem] = []
    @State private var isLoading = false
    @State private var hoveredAppId: String?
    @State private var sharingAppId: String?
    @State private var isBundling = false
    @State private var shareFileURL: URL?
    @State private var showShareSheet = false
    @State private var pendingDeleteId: String?

    // Track how many list responses we're waiting for
    @State private var pendingResponses = 0

    init(onClose: @escaping () -> Void, isExpanded: Binding<Bool> = .constant(false), daemonClient: DaemonClient, onOpenApp: ((UiSurfaceShowMessage) -> Void)? = nil) {
        self.onClose = onClose
        self._isExpanded = isExpanded
        self.daemonClient = daemonClient
        self.onOpenApp = onOpenApp
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            // Header
            HStack {
                Button(action: { withAnimation(VAnimation.fast) { isExpanded.toggle() } }) {
                    Image(systemName: isExpanded ? "arrow.down.right.and.arrow.up.left" : "arrow.up.left.and.arrow.down.right")
                        .font(.system(size: 11, weight: .medium))
                        .foregroundColor(VColor.textMuted)
                        .frame(width: 28, height: 28, alignment: .leading)
                        .contentShape(Rectangle())
                }
                .buttonStyle(.plain)
                .accessibilityLabel(isExpanded ? "Exit full screen" : "Enter full screen")

                Text("DYNAMIC")
                    .font(VFont.panelTitle)
                    .foregroundColor(VColor.textPrimary)

                Spacer()

                Button(action: onClose) {
                    Image(systemName: "xmark")
                        .font(.system(size: 12, weight: .medium))
                        .foregroundColor(VColor.textMuted)
                        .frame(width: 32, height: 32)
                        .contentShape(Rectangle())
                }
                .buttonStyle(.plain)
                .accessibilityLabel("Close Dynamic")
            }
            .padding(.horizontal, VSpacing.xl)
            .padding(.vertical, VSpacing.lg)

            Divider()
                .background(VColor.surfaceBorder)

            // Scrollable content
            ScrollView {
                Group {
                    if isLoading {
                        HStack {
                            Spacer()
                            ProgressView()
                                .controlSize(.small)
                            Spacer()
                        }
                        .frame(height: 250)
                    } else if displayItems.isEmpty {
                        VEmptyState(
                            title: "No dynamic pages",
                            subtitle: "Dynamic UIs generated by your assistant will appear here",
                            icon: "wand.and.stars"
                        )
                    } else {
                        VStack(spacing: VSpacing.md) {
                            ForEach(displayItems) { item in
                                appRow(item)
                            }
                        }
                    }
                }
                .padding(VSpacing.xl)
            }
        }
        .background(VColor.backgroundSubtle)
        .onAppear {
            fetchApps()
        }
    }

    // MARK: - App Row

    private func appRow(_ item: DisplayAppItem) -> some View {
        let isHovered = hoveredAppId == item.id
        let isBundlingThis = sharingAppId == item.id && isBundling

        return HStack(spacing: VSpacing.md) {
            // Icon
            Text(item.icon ?? "\u{1F4F1}")
                .font(.system(size: 20))
                .frame(width: 28, height: 28)

            // Name + badges + description
            VStack(alignment: .leading, spacing: 2) {
                HStack(spacing: VSpacing.xs) {
                    Text(item.name)
                        .font(VFont.bodyBold)
                        .foregroundColor(VColor.textPrimary)
                        .lineLimit(1)

                    if item.isShared {
                        sharedBadge
                    }

                    if let tier = item.trustTier {
                        trustBadge(tier: tier)
                    }
                }

                if let description = item.description, !description.isEmpty {
                    Text(description)
                        .font(VFont.caption)
                        .foregroundColor(VColor.textSecondary)
                        .lineLimit(2)
                }

                Text(item.dateLabel)
                    .font(VFont.small)
                    .foregroundColor(VColor.textMuted)
            }

            Spacer()

            // Action buttons — visible on hover
            let showingShareSheet = showShareSheet && sharingAppId == item.id
            if isHovered || isBundlingThis || showingShareSheet {
                HStack(spacing: VSpacing.xs) {
                    if isBundlingThis {
                        ProgressView()
                            .controlSize(.mini)
                            .frame(width: 24, height: 24)

                        // Keep the ShareSheetButton in the view tree during
                        // bundling so the NSButton stays attached to a window.
                        // It's hidden but will be ready when bundling completes.
                        shareButton(for: item)
                            .frame(width: 0, height: 0)
                            .opacity(0)
                    } else {
                        shareButton(for: item)

                        if item.isShared {
                            deleteButton(for: item)
                        }
                    }
                }
            }
        }
        .padding(VSpacing.lg)
        .background(isHovered ? Slate._800 : Slate._900)
        .clipShape(RoundedRectangle(cornerRadius: VRadius.md))
        .overlay(
            RoundedRectangle(cornerRadius: VRadius.md)
                .stroke(item.isShared ? Violet._700.opacity(0.4) : Emerald._700.opacity(0.4), lineWidth: 1)
        )
        .contentShape(Rectangle())
        .onTapGesture {
            openApp(item)
        }
        .onHover { hovering in
            withAnimation(VAnimation.fast) {
                if hovering {
                    hoveredAppId = item.id
                } else if !showShareSheet {
                    hoveredAppId = nil
                }
            }
        }
    }

    // MARK: - Badges

    private var sharedBadge: some View {
        HStack(spacing: 2) {
            Image(systemName: "person.2.fill")
                .font(.system(size: 8))
            Text("Shared")
                .font(VFont.small)
        }
        .foregroundColor(Violet._400)
        .padding(.horizontal, 5)
        .padding(.vertical, 1)
        .background(Violet._900.opacity(0.5))
        .clipShape(RoundedRectangle(cornerRadius: VRadius.sm))
    }

    private func trustBadge(tier: String) -> some View {
        let (icon, color): (String, Color) = {
            switch tier {
            case "verified":
                return ("checkmark.seal.fill", VColor.success)
            case "signed":
                return ("checkmark.seal", VColor.textSecondary)
            case "unsigned":
                return ("exclamationmark.triangle.fill", VColor.warning)
            case "tampered":
                return ("xmark.seal.fill", VColor.error)
            default:
                return ("questionmark.circle", VColor.textMuted)
            }
        }()

        return Image(systemName: icon)
            .font(.system(size: 10))
            .foregroundColor(color)
    }

    // MARK: - Buttons

    @ViewBuilder
    private func shareButton(for item: DisplayAppItem) -> some View {
        if let localId = item.localAppId {
            ZStack {
                ShareSheetButton(
                    items: shareFileURL != nil && sharingAppId == item.id ? [shareFileURL!] : [],
                    isPresented: Binding(
                        get: { showShareSheet && sharingAppId == item.id },
                        set: { showShareSheet = $0 }
                    )
                )
                .frame(width: 0, height: 0)
                .opacity(0)

                VIconButton(label: "Share", icon: "square.and.arrow.up", iconOnly: true) {
                    bundleAndShare(appId: localId, itemId: item.id)
                }
            }
        } else if item.isShared, let uuid = item.sharedUUID {
            ZStack {
                ShareSheetButton(
                    items: shareFileURL != nil && sharingAppId == item.id ? [shareFileURL!] : [],
                    isPresented: Binding(
                        get: { showShareSheet && sharingAppId == item.id },
                        set: { showShareSheet = $0 }
                    )
                )
                .frame(width: 0, height: 0)
                .opacity(0)

                VIconButton(label: "Share", icon: "square.and.arrow.up", iconOnly: true) {
                    reshareApp(uuid: uuid, itemId: item.id)
                }
            }
        }
    }

    private func deleteButton(for item: DisplayAppItem) -> some View {
        VIconButton(label: "Delete", icon: "trash", iconOnly: true) {
            deleteSharedApp(item)
        }
    }

    // MARK: - Data Fetching

    @State private var localApps: [AppItem] = []
    @State private var sharedApps: [SharedAppItem] = []

    private func fetchApps() {
        isLoading = true
        pendingResponses = 2

        Task { @MainActor in
            daemonClient.onAppsListResponse = { response in
                self.localApps = response.apps
                self.pendingResponses -= 1
                if self.pendingResponses <= 0 {
                    self.buildDisplayItems()
                    self.isLoading = false
                }
            }

            daemonClient.onSharedAppsListResponse = { response in
                self.sharedApps = response.apps
                self.pendingResponses -= 1
                if self.pendingResponses <= 0 {
                    self.buildDisplayItems()
                    self.isLoading = false
                }
            }

            // Handle daemon-side errors that arrive as generic `error` messages
            // instead of typed responses — reset loading/bundling state so the UI
            // never gets permanently stuck.
            daemonClient.onError = { _ in
                if self.isLoading {
                    self.pendingResponses -= 1
                    if self.pendingResponses <= 0 {
                        self.buildDisplayItems()
                        self.isLoading = false
                    }
                }
                if self.isBundling {
                    self.isBundling = false
                    self.sharingAppId = nil
                }
            }

            do {
                try daemonClient.sendAppsList()
            } catch {
                pendingResponses -= 1
            }

            do {
                try daemonClient.sendSharedAppsList()
            } catch {
                pendingResponses -= 1
            }

            if pendingResponses <= 0 {
                buildDisplayItems()
                isLoading = false
            }
        }
    }

    private func buildDisplayItems() {
        var items: [DisplayAppItem] = []

        // Local apps
        for app in localApps {
            items.append(DisplayAppItem(
                id: "local-\(app.id)",
                name: app.name,
                description: app.description,
                icon: app.icon,
                dateLabel: formatDate(app.createdAt),
                isShared: false,
                trustTier: nil,
                signerDisplayName: nil,
                localAppId: app.id,
                sharedUUID: nil
            ))
        }

        // Shared apps
        for app in sharedApps {
            items.append(DisplayAppItem(
                id: "shared-\(app.uuid)",
                name: app.name,
                description: app.description,
                icon: app.icon,
                dateLabel: formatISO(app.installedAt),
                isShared: true,
                trustTier: app.trustTier,
                signerDisplayName: app.signerDisplayName,
                localAppId: nil,
                sharedUUID: app.uuid
            ))
        }

        displayItems = items
    }

    // MARK: - Open App

    private func openApp(_ item: DisplayAppItem) {
        if let localId = item.localAppId {
            // Local apps: ask the daemon to open via ui_surface_show.
            // When onOpenApp is set, the daemon's response will be intercepted
            // by SurfaceManager and routed to the workspace (see PR 5).
            try? daemonClient.sendAppOpen(appId: localId)
        } else if let uuid = item.sharedUUID {
            // Shared apps: construct surface from unpacked files on disk
            // Sanitize to prevent XSS — name comes from external bundle metadata
            let safeName = htmlEscape(item.name)
            let sanitizedUUID = uuid
                .replacingOccurrences(of: "\\", with: "")
                .replacingOccurrences(of: "'", with: "")
            let entryURL = "\(VellumAppSchemeHandler.scheme)://\(sanitizedUUID)/index.html"
            let html = """
            <!DOCTYPE html>
            <html>
            <head><meta charset="utf-8"><title>\(safeName)</title></head>
            <body><script>window.location.href = '\(entryURL)';</script></body>
            </html>
            """
            let surfaceMsg = UiSurfaceShowMessage(
                sessionId: "shared-app",
                surfaceId: "shared-app-\(uuid)",
                surfaceType: "dynamic_page",
                title: item.name,
                data: AnyCodable(["html": html]),
                actions: nil,
                display: "panel"
            )
            if let onOpenApp {
                onOpenApp(surfaceMsg)
            } else {
                daemonClient.onSurfaceShow?(surfaceMsg)
            }
        }
    }

    // MARK: - Bundle & Share

    private func bundleAndShare(appId: String, itemId: String) {
        guard !isBundling else { return }
        sharingAppId = itemId
        isBundling = true

        Task { @MainActor in
            daemonClient.onBundleAppResponse = { response in
                let url = URL(fileURLWithPath: response.bundlePath)
                self.shareFileURL = url
                self.isBundling = false
                self.showShareSheet = true
            }

            do {
                try daemonClient.sendBundleApp(appId: appId)
            } catch {
                isBundling = false
                sharingAppId = nil
            }
        }
    }

    private func reshareApp(uuid: String, itemId: String) {
        // Share the existing unpacked directory as a folder
        let appDir = BundleSandbox.sharedAppsDirectory.appendingPathComponent(uuid)
        guard FileManager.default.fileExists(atPath: appDir.path) else { return }
        sharingAppId = itemId
        shareFileURL = appDir
        showShareSheet = true
    }

    // MARK: - Delete Shared App

    private func deleteSharedApp(_ item: DisplayAppItem) {
        guard let uuid = item.sharedUUID else { return }

        Task { @MainActor in
            daemonClient.onSharedAppDeleteResponse = { response in
                if response.success {
                    self.sharedApps.removeAll { $0.uuid == uuid }
                    self.buildDisplayItems()
                }
            }

            do {
                try daemonClient.sendSharedAppDelete(uuid: uuid)
            } catch {
                // Silently fail
            }
        }
    }

    // MARK: - Helpers

    private func formatDate(_ epochMs: Int) -> String {
        let date = Date(timeIntervalSince1970: Double(epochMs) / 1000)
        let formatter = RelativeDateTimeFormatter()
        formatter.unitsStyle = .abbreviated
        return formatter.localizedString(for: date, relativeTo: Date())
    }

    private func formatISO(_ isoString: String) -> String {
        let isoFormatter = ISO8601DateFormatter()
        guard let date = isoFormatter.date(from: isoString) else { return isoString }
        let formatter = RelativeDateTimeFormatter()
        formatter.unitsStyle = .abbreviated
        return formatter.localizedString(for: date, relativeTo: Date())
    }

    private func htmlEscape(_ string: String) -> String {
        string
            .replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
            .replacingOccurrences(of: "'", with: "&#39;")
    }
}

#Preview {
    GeneratedPanel(onClose: {}, isExpanded: .constant(false), daemonClient: DaemonClient())
}
