/**
 * CES approval bridge.
 *
 * Translates a CES `approval_required` response into an interactive
 * confirmation prompt using the existing PermissionPrompter transport.
 * When the guardian approves, the bridge commits the decision back to CES
 * via the `record_grant` RPC rather than writing into `trust.json`.
 *
 * Design principles:
 * - The assistant never sees raw secret values. The rendered proposal text
 *   comes from CES (generated by `@vellumai/ces-contracts` rendering).
 * - Approved decisions are persisted inside CES, not in local trust rules.
 * - After approval the bridge returns a `grantId` so the caller can retry
 *   the original tool invocation with the grant attached.
 */

import type {
  ApprovalRequired,
  RecordGrantResponse,
} from "@vellumai/ces-contracts";

import type { PermissionPrompter } from "../permissions/prompter.js";
import type { UserDecision } from "../permissions/types.js";
import { getLogger } from "../util/logger.js";
import type { CesClient } from "./client.js";

const log = getLogger("ces-approval-bridge");

// ---------------------------------------------------------------------------
// Decision mapping
// ---------------------------------------------------------------------------

/**
 * CES approval decisions that the bridge presents to the guardian.
 *
 * Maps the existing confirmation transport decisions to CES grant semantics:
 * - `allow`          -> approved (single-use grant, no TTL)
 * - `allow_10m`      -> approved (temporary grant, 10-minute TTL)
 * - `allow_thread`   -> approved (session-scoped grant, no TTL but session-bound)
 * - `always_allow`   -> approved (persistent grant, no expiry)
 * - `deny`           -> denied
 * - `always_deny`    -> denied
 */
export interface CesApprovalDecision {
  /** The CES grant decision: approved or denied. */
  grantDecision: "approved" | "denied";
  /** ISO-8601 duration for temporary grants. Undefined for single-use or persistent. */
  ttl: string | undefined;
  /** The original user decision from the confirmation transport. */
  userDecision: UserDecision;
}

function mapUserDecisionToCesDecision(
  decision: UserDecision,
): CesApprovalDecision {
  switch (decision) {
    case "allow":
      return {
        grantDecision: "approved",
        ttl: undefined,
        userDecision: decision,
      };
    case "allow_10m":
      return {
        grantDecision: "approved",
        ttl: "PT10M",
        userDecision: decision,
      };
    case "allow_thread":
      // Thread-scoped grants don't have a wall-clock TTL — they are bound
      // to the session lifetime. CES handles the session binding; we pass
      // no TTL so the grant remains active until the session ends.
      return {
        grantDecision: "approved",
        ttl: undefined,
        userDecision: decision,
      };
    case "always_allow":
    case "always_allow_high_risk":
      // Persistent grant — no expiry. CES stores it with expiresAt: null.
      return {
        grantDecision: "approved",
        ttl: undefined,
        userDecision: decision,
      };
    case "deny":
    case "always_deny":
      return {
        grantDecision: "denied",
        ttl: undefined,
        userDecision: decision,
      };
    case "temporary_override":
      return {
        grantDecision: "approved",
        ttl: undefined,
        userDecision: decision,
      };
    default: {
      // Exhaustiveness guard — treat unknown decisions as denials.
      const _exhaustive: never = decision;
      return {
        grantDecision: "denied",
        ttl: undefined,
        userDecision: decision,
      };
    }
  }
}

// ---------------------------------------------------------------------------
// Bridge result
// ---------------------------------------------------------------------------

export type CesApprovalBridgeResult =
  | {
      outcome: "approved";
      grantId: string;
      userDecision: UserDecision;
    }
  | {
      outcome: "denied";
      userDecision: UserDecision;
    }
  | {
      outcome: "timeout";
    }
  | {
      outcome: "error";
      message: string;
    };

// ---------------------------------------------------------------------------
// Bridge function
// ---------------------------------------------------------------------------

/**
 * Present a CES approval request to the guardian using the existing
 * confirmation prompt infrastructure, then commit the decision to CES
 * via the `record_grant` RPC.
 *
 * @param approval - The `approval_required` payload from CES.
 * @param prompter - The PermissionPrompter that sends confirmation_request
 *   messages to the connected client.
 * @param cesClient - The CES RPC client for committing the grant decision.
 * @param options - Optional configuration for the bridge.
 * @returns The outcome of the approval flow.
 */
export async function bridgeCesApproval(
  approval: ApprovalRequired,
  prompter: PermissionPrompter,
  cesClient: CesClient,
  options?: {
    /** Whether an interactive client is connected. When false, auto-deny. */
    isInteractive?: boolean;
    /** Session ID for the confirmation prompt. */
    sessionId?: string;
    /** Abort signal for cooperative cancellation. */
    signal?: AbortSignal;
  },
): Promise<CesApprovalBridgeResult> {
  const { proposal, renderedProposal, proposalHash, sessionId } = approval;

  // Non-interactive sessions have no client to respond — fail closed.
  if (options?.isInteractive === false) {
    log.info(
      {
        event: "ces_approval_bridge_non_interactive",
        proposalHash,
        sessionId,
      },
      "CES approval request denied: non-interactive session",
    );
    return { outcome: "denied", userDecision: "deny" };
  }

  // Build the tool name and input for the confirmation prompt. The tool
  // name uses a `ces:` prefix so the client can distinguish CES approval
  // requests from regular tool confirmation prompts.
  const toolName = `ces:${proposal.type}`;
  const input: Record<string, unknown> = {
    credentialHandle: proposal.credentialHandle,
    purpose: proposal.purpose,
    renderedProposal,
  };

  if (proposal.type === "http") {
    input.method = proposal.method;
    input.url = proposal.url;
  } else if (proposal.type === "command") {
    input.command = proposal.command;
  }

  // Present the confirmation prompt to the guardian. The prompter handles
  // timeouts and abort signals internally.
  const response = await prompter.prompt(
    toolName,
    input,
    "high", // CES approval requests are always high-risk
    [], // No allowlist options — CES manages its own grant patterns
    [], // No scope options — CES manages scope internally
    undefined, // No file diff
    undefined, // Not sandboxed
    options?.sessionId,
    "host", // CES operations target the host
    false, // Persistent decisions are managed by CES, not trust.json
    options?.signal,
    ["allow_10m", "allow_thread"], // Offer temporary approval options
  );

  const cesDecision = mapUserDecisionToCesDecision(response.decision);

  log.info(
    {
      event: "ces_approval_bridge_decision",
      proposalHash,
      sessionId,
      userDecision: response.decision,
      grantDecision: cesDecision.grantDecision,
      ttl: cesDecision.ttl,
    },
    `CES approval bridge: guardian decision is "${cesDecision.grantDecision}"`,
  );

  if (cesDecision.grantDecision === "denied") {
    return { outcome: "denied", userDecision: response.decision };
  }

  // Commit the approved grant to CES via record_grant RPC.
  try {
    const grantResponse: RecordGrantResponse = await cesClient.call(
      "record_grant",
      {
        decision: {
          proposal,
          proposalHash,
          decision: cesDecision.grantDecision,
          decidedBy: "guardian",
          decidedAt: new Date().toISOString(),
          reason: response.decisionContext,
          ttl: cesDecision.ttl,
        },
        sessionId,
      },
    );

    if (!grantResponse.success) {
      const errorMsg =
        grantResponse.error?.message ?? "Unknown error recording grant";
      log.warn(
        {
          event: "ces_approval_bridge_record_failed",
          proposalHash,
          sessionId,
          error: errorMsg,
        },
        "CES record_grant RPC failed",
      );
      return { outcome: "error", message: errorMsg };
    }

    const grantId = grantResponse.grant?.grantId;
    if (!grantId) {
      log.warn(
        {
          event: "ces_approval_bridge_no_grant_id",
          proposalHash,
          sessionId,
        },
        "CES record_grant succeeded but returned no grantId",
      );
      return {
        outcome: "error",
        message: "Grant recorded but no grantId returned",
      };
    }

    log.info(
      {
        event: "ces_approval_bridge_granted",
        proposalHash,
        sessionId,
        grantId,
        userDecision: response.decision,
      },
      "CES approval bridge: grant recorded successfully",
    );

    return {
      outcome: "approved",
      grantId,
      userDecision: response.decision,
    };
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    log.warn(
      {
        event: "ces_approval_bridge_rpc_error",
        proposalHash,
        sessionId,
        error: msg,
      },
      "CES record_grant RPC call failed",
    );
    return { outcome: "error", message: msg };
  }
}
