import Foundation
import VellumAssistantShared

typealias ImageURLClassification = VellumAssistantShared.ImageURLClassification
typealias ImageURLClassifier = VellumAssistantShared.ImageURLClassifier
