/**
 * Canonical catalog of built-in web-search providers.
 *
 * This is the single source of truth that drives:
 *
 *   1. The config-schema enum (`VALID_WEB_SEARCH_PROVIDERS` in
 *      `assistant/src/config/schemas/services.ts`).
 *   2. The search-provider env-var map (`SEARCH_PROVIDER_ENV_VAR_NAMES`
 *      in `provider-env-vars.ts`).
 *   3. The API-key provider set (`SEARCH_API_KEY_PROVIDERS` in
 *      `provider-secret-catalog.ts`).
 *   4. (Indirect, via `meta/web-search-provider-catalog.json` generated by
 *      `assistant/scripts/sync-web-search-catalog.ts`) the CLI mirror in
 *      `cli/src/shared/provider-env-vars.ts` and the web vendored catalog
 *      in `vellum-assistant-platform`.
 *
 * Mirrors the pattern from `model-catalog.ts` (Provider Expansion Phase 3
 * for LLM providers). When introducing a new built-in web-search provider,
 * the daemon-side changes collapse to:
 *
 *   1. Add a new executor in `tools/network/web-search.ts`.
 *   2. Register an adapter in the `WEB_SEARCH_ADAPTERS` table.
 *   3. Add the id to `SEARCH_PROVIDER_IDS` and a catalog entry below.
 *   4. Run `bun run sync:web-search-catalog` to regenerate
 *      `meta/web-search-provider-catalog.json`.
 *
 * The split between adapter (which carries the executor) and catalog (which
 * carries metadata) keeps the catalog purely declarative — adding an entry
 * never forces a code rebuild downstream and the JSON projection stays
 * trivial.
 */

/**
 * All provider ids accepted by the web-search config schema, as a const
 * tuple so that `z.enum(SEARCH_PROVIDER_IDS)` preserves literal types in
 * `z.infer<>`.  Follows the same pattern as `VALID_INFERENCE_PROVIDERS`
 * and `VALID_IMAGE_GEN_PROVIDERS` in `config/schemas/services.ts`.
 */
export const SEARCH_PROVIDER_IDS = [
  "inference-provider-native",
  "perplexity",
  "brave",
  "tavily",
] as const;

export type SearchProviderId = (typeof SEARCH_PROVIDER_IDS)[number];

export type SearchProviderKind = "managed" | "byok";

export interface SearchProviderCatalogEntry {
  /** Stable provider identifier. Matches config + secret-catalog values. */
  readonly id: SearchProviderId;
  /** Short display name used by picker UIs. */
  readonly displayName: string;
  /**
   * Optional long display name for prose contexts (marketing docs,
   * privacy notices). Defaults to {@link displayName} when omitted.
   */
  readonly displayNameLong?: string;
  /** Authentication style. `managed` providers are routed through the
   *  inference provider; `byok` providers require a user-supplied key. */
  readonly kind: SearchProviderKind;
  /** Placeholder shown in the API-key input. BYOK providers only. */
  readonly apiKeyPrefix?: string;
  /** Environment variable name carrying the API key. BYOK providers only. */
  readonly envVar?: string;
  /** Secret-catalog key (the bare provider name accepted by
   *  `getProviderKeyAsync`). BYOK providers only. */
  readonly secretKey?: string;
  /** Position in the daemon fallback chain (lower = earlier). BYOK only. */
  readonly fallbackOrder?: number;
  /** Privacy-policy URL surfaced in marketing data-sharing docs.
   *  BYOK providers only. */
  readonly privacyPolicyUrl?: string;
}

export const SEARCH_PROVIDER_CATALOG: readonly SearchProviderCatalogEntry[] = [
  {
    id: "inference-provider-native",
    displayName: "Provider Native",
    kind: "managed",
  },
  {
    id: "perplexity",
    displayName: "Perplexity",
    kind: "byok",
    apiKeyPrefix: "pplx-...",
    envVar: "PERPLEXITY_API_KEY",
    secretKey: "perplexity",
    fallbackOrder: 1,
    privacyPolicyUrl: "https://www.perplexity.ai/hub/legal/privacy-policy",
  },
  {
    id: "brave",
    displayName: "Brave",
    displayNameLong: "Brave Search",
    kind: "byok",
    apiKeyPrefix: "BSA...",
    envVar: "BRAVE_API_KEY",
    secretKey: "brave",
    fallbackOrder: 2,
    privacyPolicyUrl: "https://search.brave.com/help/privacy-policy",
  },
  {
    id: "tavily",
    displayName: "Tavily",
    kind: "byok",
    apiKeyPrefix: "tvly-...",
    envVar: "TAVILY_API_KEY",
    secretKey: "tavily",
    fallbackOrder: 3,
    privacyPolicyUrl: "https://tavily.com/privacy",
  },
];

/** Catalog entries that store an API key under their bare provider name. */
export const BYOK_SEARCH_PROVIDERS: readonly SearchProviderCatalogEntry[] =
  SEARCH_PROVIDER_CATALOG.filter((p) => p.kind === "byok");

/** BYOK provider ids, ordered by `fallbackOrder` (ascending). */
export const SEARCH_PROVIDER_FALLBACK_ORDER: readonly string[] = BYOK_SEARCH_PROVIDERS
  .slice()
  .sort((a, b) => (a.fallbackOrder ?? 0) - (b.fallbackOrder ?? 0))
  .map((p) => p.id);

/** Look up a single catalog entry by id. Returns `undefined` if unknown. */
export function getSearchProvider(
  id: string,
): SearchProviderCatalogEntry | undefined {
  return SEARCH_PROVIDER_CATALOG.find((p) => p.id === id);
}
