/**
 * A2A (Assistant-to-Assistant) message envelope contract.
 *
 * Gateway-local copy of assistant/src/runtime/a2a/message-contract.ts.
 * Duplicated here because the gateway's tsconfig rootDir does not include
 * the assistant package. Keep in sync manually until the contract is
 * extracted to a shared package.
 */

// ---------------------------------------------------------------------------
// Envelope types
// ---------------------------------------------------------------------------

/** Authenticated message between paired assistants. */
export interface A2AMessageEnvelope {
  version: "v1";
  type: "message";
  senderAssistantId: string;
  messageId: string; // idempotency key
  content: string;
}

/** Pairing request — sent by initiator to target (unauthenticated). */
export interface A2APairingRequest {
  version: "v1";
  type: "pairing_request";
  senderAssistantId: string;
  senderGatewayUrl: string; // initiator's gateway for callback
  inviteCode: string; // one-time code generated by initiator
}

/** Pairing acceptance — sent by target back to initiator (unauthenticated). */
export interface A2APairingAccepted {
  version: "v1";
  type: "pairing_accepted";
  senderAssistantId: string;
  inviteCode: string; // echoed back to bind to original request
  inboundToken: string; // token for initiator to use when contacting target
}

/** Pairing finalization — sent by initiator to target (authenticated). */
export interface A2APairingFinalize {
  version: "v1";
  type: "pairing_finalize";
  senderAssistantId: string;
  inviteCode: string; // echoed to bind to original request
  inboundToken: string; // token for target to use when contacting initiator
}

/** Pairing verification — sent by initiator to target (unauthenticated). */
export interface A2APairingVerify {
  version: "v1";
  type: "pairing_verify";
  senderAssistantId: string;
  inviteCode: string; // binds to the original pairing request
  verificationCode: string; // 6-digit code from the target's guardian
}

export type A2AEnvelope =
  | A2AMessageEnvelope
  | A2APairingRequest
  | A2APairingAccepted
  | A2APairingFinalize
  | A2APairingVerify;

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

const VALID_TYPES = new Set([
  "message",
  "pairing_request",
  "pairing_accepted",
  "pairing_finalize",
  "pairing_verify",
] as const);

/** Maximum byte length for `content` in message envelopes. 256 KiB. */
const MAX_CONTENT_BYTES = 256 * 1024;

export class A2AValidationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "A2AValidationError";
  }
}

/**
 * Parse and validate an A2A envelope from an unknown payload.
 *
 * Fails closed: any missing or malformed field causes rejection.
 * Extra fields are silently ignored (forward-compatible).
 */
export function parseA2AEnvelope(payload: unknown): A2AEnvelope {
  if (payload == null || typeof payload !== "object") {
    throw new A2AValidationError("Payload must be a non-null object");
  }

  const obj = payload as Record<string, unknown>;

  // -- version --
  if (obj.version !== "v1") {
    throw new A2AValidationError(
      `Unsupported version: ${JSON.stringify(obj.version)}`,
    );
  }

  // -- type discriminant --
  if (
    typeof obj.type !== "string" ||
    !VALID_TYPES.has(obj.type as A2AEnvelope["type"])
  ) {
    throw new A2AValidationError(`Invalid type: ${JSON.stringify(obj.type)}`);
  }

  // -- common required string --
  requireNonEmptyString(obj, "senderAssistantId");

  const type = obj.type as A2AEnvelope["type"];

  switch (type) {
    case "message":
      return parseMessage(obj);
    case "pairing_request":
      return parsePairingRequest(obj);
    case "pairing_accepted":
      return parsePairingAccepted(obj);
    case "pairing_finalize":
      return parsePairingFinalize(obj);
    case "pairing_verify":
      return parsePairingVerify(obj);
    default: {
      // Exhaustiveness check — should never reach here after the Set guard.
      const _exhaustive: never = type;
      throw new A2AValidationError(`Unexpected type: ${_exhaustive}`);
    }
  }
}

// ---------------------------------------------------------------------------
// Per-variant parsers
// ---------------------------------------------------------------------------

function parseMessage(obj: Record<string, unknown>): A2AMessageEnvelope {
  requireNonEmptyString(obj, "messageId");
  requireString(obj, "content"); // content may be empty string

  const content = obj.content as string;
  if (new TextEncoder().encode(content).byteLength > MAX_CONTENT_BYTES) {
    throw new A2AValidationError(
      `content exceeds maximum size of ${MAX_CONTENT_BYTES} bytes`,
    );
  }

  return {
    version: "v1",
    type: "message",
    senderAssistantId: obj.senderAssistantId as string,
    messageId: obj.messageId as string,
    content,
  };
}

function parsePairingRequest(obj: Record<string, unknown>): A2APairingRequest {
  requireNonEmptyString(obj, "senderGatewayUrl");
  requireNonEmptyString(obj, "inviteCode");

  return {
    version: "v1",
    type: "pairing_request",
    senderAssistantId: obj.senderAssistantId as string,
    senderGatewayUrl: obj.senderGatewayUrl as string,
    inviteCode: obj.inviteCode as string,
  };
}

function parsePairingAccepted(
  obj: Record<string, unknown>,
): A2APairingAccepted {
  requireNonEmptyString(obj, "inviteCode");
  requireNonEmptyString(obj, "inboundToken");

  return {
    version: "v1",
    type: "pairing_accepted",
    senderAssistantId: obj.senderAssistantId as string,
    inviteCode: obj.inviteCode as string,
    inboundToken: obj.inboundToken as string,
  };
}

function parsePairingFinalize(
  obj: Record<string, unknown>,
): A2APairingFinalize {
  requireNonEmptyString(obj, "inviteCode");
  requireNonEmptyString(obj, "inboundToken");

  return {
    version: "v1",
    type: "pairing_finalize",
    senderAssistantId: obj.senderAssistantId as string,
    inviteCode: obj.inviteCode as string,
    inboundToken: obj.inboundToken as string,
  };
}

function parsePairingVerify(obj: Record<string, unknown>): A2APairingVerify {
  requireNonEmptyString(obj, "inviteCode");
  requireNonEmptyString(obj, "verificationCode");

  return {
    version: "v1",
    type: "pairing_verify",
    senderAssistantId: obj.senderAssistantId as string,
    inviteCode: obj.inviteCode as string,
    verificationCode: obj.verificationCode as string,
  };
}

// ---------------------------------------------------------------------------
// Field helpers
// ---------------------------------------------------------------------------

function requireString(obj: Record<string, unknown>, field: string): void {
  if (typeof obj[field] !== "string") {
    throw new A2AValidationError(`Missing or invalid field: ${field}`);
  }
}

function requireNonEmptyString(
  obj: Record<string, unknown>,
  field: string,
): void {
  requireString(obj, field);
  if ((obj[field] as string).length === 0) {
    throw new A2AValidationError(`Field must not be empty: ${field}`);
  }
}
