/**
 * Cast — activation-surface prototype.
 *
 * A packed roster of characters built from the existing avatar vocabulary
 * (`BUNDLED_COMPONENTS`: body shape + eye style + color). This is the visual
 * baseline — the same "dudes" the avatar builder produces — so the prototype
 * proves personality with the real art, not stand-in sketches.
 *
 * The roster is generated by walking body × eyes × color with coprime strides
 * so a large set stays maximally varied (no two neighbours alike). Each
 * character gets a stable hardcoded name, a one-shot hover animation, and a
 * reaction derived from its eye style.
 */

import { BUNDLED_COMPONENTS } from "@/utils/avatar-bundled-components";

export const COMPONENTS = BUNDLED_COMPONENTS;

const BODIES = BUNDLED_COMPONENTS.bodyShapes.map((b) => b.id);
const EYES = BUNDLED_COMPONENTS.eyeStyles.map((e) => e.id);
const COLORS = BUNDLED_COMPONENTS.colors.map((c) => c.id);

/** One-shot animations a tile plays on hover. */
export type HoverAnim = "jump" | "flip" | "wiggle" | "spin";

/**
 * Autonomous Beat-2 reaction, keyed to the eye style so expression and motion
 * agree. These avatars are a single composited SVG (no limbs), so reactions
 * are whole-character motion: "crosses arms" reads as a defiant huff, "yawns"
 * as a slow stretch, etc.
 */
export type Reaction =
  | "huff"
  | "yawn"
  | "peer"
  | "spin"
  | "startle"
  | "shy"
  | "sway"
  | "tilt"
  | "woozy";

const REACTION_BY_EYES: Record<string, Reaction> = {
  angry: "huff",
  grumpy: "yawn",
  curious: "peer",
  goofy: "spin",
  surprised: "startle",
  bashful: "shy",
  gentle: "sway",
  quirky: "tilt",
  dazed: "woozy",
};

export interface CastCharacter {
  id: string;
  name: string;
  bodyShape: string;
  eyeStyle: string;
  color: string;
  hover: HoverAnim;
  reaction: Reaction;
}

const HOVERS: HoverAnim[] = ["jump", "flip", "wiggle", "spin"];

/** Stable, characterful names — keyed by body+eyes combo (see below). */
const NAMES = [
  "Mossback", "Nimbus", "Sprig", "Blaze", "Whisper",
  "Prickle", "Waffles", "Daisy", "Comet", "Pip",
  "Tater", "Juniper", "Scoot", "Bramble", "Doodle",
  "Pebble", "Sunny", "Grump", "Twirl", "Cinder",
  "Nessie", "Bop", "Fennel", "Quill", "Marbles",
  "Huckle", "Snooze", "Zigzag", "Poppy", "Biscuit",
  "Wobble", "Gus", "Clementine", "Fizz", "Noodle", "Bramwell",
  "Tugboat", "Olive", "Custard", "Squeak", "Bandit", "Maple",
];

/**
 * Deterministic integer hash. Used to scatter each axis independently of the
 * grid's column count — a linear `i * stride` banded into vertical stripes
 * once it aligned with the 6-wide grid, so we hash instead. Not random (no
 * Date/Math.random), just well-mixed and stable across reloads.
 */
export function hash(n: number, salt: number): number {
  let v = Math.imul(n ^ (salt * 0x9e3779b1), 2654435761);
  v ^= v >>> 15;
  v = Math.imul(v, 0x85ebca6b);
  v ^= v >>> 13;
  return v >>> 0;
}

/** Large pool so a full-bleed crowd can be sliced to fit any viewport — the
 * floor extends well past the window edges and grows with the window, so this
 * needs enough characters to cover large screens without repeating. */
const COUNT = 720;

/**
 * Generate the roster. Each axis is hashed with its own salt so neighbours
 * differ on body, eyes, and color regardless of how many columns the grid
 * lays out — a true mix-and-match field. Names are keyed to the body+eyes
 * combo so the same character always reads with the same name.
 */
export const CAST: CastCharacter[] = Array.from({ length: COUNT }, (_, i) => {
  const bodyIdx = hash(i, 1) % BODIES.length;
  const eyeIdx = hash(i, 2) % EYES.length;
  const bodyShape = BODIES[bodyIdx];
  const eyeStyle = EYES[eyeIdx];
  const color = COLORS[hash(i, 3) % COLORS.length];
  return {
    id: `cast-${i}-${bodyShape}-${eyeStyle}`,
    name: NAMES[(bodyIdx * EYES.length + eyeIdx) % NAMES.length],
    bodyShape,
    eyeStyle,
    color,
    hover: HOVERS[hash(i, 4) % HOVERS.length],
    reaction: REACTION_BY_EYES[eyeStyle] ?? "sway",
  };
});

/**
 * Build a single character from an explicit body + eyes + color triple — the
 * output of the starter-select / customization flow. Name, reaction, and hover
 * are derived the same way the generated roster derives them, so a hand-built
 * character reads identically to one plucked from the crowd.
 */
export function buildCharacter(
  bodyShape: string,
  eyeStyle: string,
  color: string,
): CastCharacter {
  const bodyIdx = Math.max(0, BODIES.indexOf(bodyShape));
  const eyeIdx = Math.max(0, EYES.indexOf(eyeStyle));
  return {
    id: `cast-pick-${bodyShape}-${eyeStyle}-${color}`,
    name: NAMES[(bodyIdx * EYES.length + eyeIdx) % NAMES.length],
    bodyShape,
    eyeStyle,
    color,
    hover: HOVERS[(bodyIdx + eyeIdx) % HOVERS.length],
    reaction: REACTION_BY_EYES[eyeStyle] ?? "sway",
  };
}
