import {
  type DiskPressureStatusResponse,
  DiskPressureStatusResponseSchema,
} from "@vellumai/assistant-api";

import {
  assistantsActivateCreate,
  assistantsBackupsCreate,
  assistantsBackupsRestoreCreate,
  assistantsBackupsRetrieve,
  assistantsHatchCreate,
  assistantsList,
  assistantsRestartDetailCreate,
  assistantsRetireDetailDestroy,
  assistantsRetireDestroy,
  assistantsRetrieve,
} from "@/generated/api/sdk.gen";
import type {
  Assistant as GeneratedAssistant,
  HatchAssistantRequest,
} from "@/generated/api/types.gen";
import {
  backupsCreatePost,
  backupsGet,
  backupsRestorePost,
  diskpressureAcknowledgePost,
  diskpressureStatusGet,
  healthzGet,
} from "@/generated/daemon/sdk.gen";
import type { HealthzGetResponse } from "@/generated/daemon/types.gen";
import { assertHasResponse, toErrorObject } from "@/utils/api-errors";
import { isGatewayAuthMode } from "@/lib/auth/gateway-session";
import { getSelectedAssistant } from "@/lib/local-mode";
import { getSelfHostedIngressUrl } from "@/lib/self-hosted/connection";

// DO NOT ADD ONTO THIS FILE. USE THE AUTOGENERATED TANSTACK QUERY HOOKS INSTEAD.
// THIS IS HERE JUST FOR LEGACY COMPATIBILITY.

export type HatchInput = HatchAssistantRequest;
export type Assistant = GeneratedAssistant;

export type HatchResult =
  | { ok: true; status: number; data: Assistant }
  | { ok: false; status: number; error: Record<string, unknown> };

export type GetAssistantResult =
  | { ok: true; status: number; data: Assistant }
  | { ok: false; status: number; error: Record<string, unknown> };

export type GetHealthzResult =
  | { ok: true; status: number; data: HealthzGetResponse }
  | { ok: false; status: number; error: Record<string, unknown> };

export type GetAssistantDiskPressureStatusResult =
  | { ok: true; status: number; data: DiskPressureStatusResponse }
  | { ok: false; status: number; error: Record<string, unknown> };

export type AcknowledgeAssistantDiskPressureResult =
  | { ok: true; status: number; data: DiskPressureStatusResponse }
  | { ok: false; status: number; error: Record<string, unknown> };

/**
 * Hatch a managed assistant.
 *
 * `mode` maps to the platform's hatch semantics:
 *   - `ensure` (server default when omitted): return an existing managed
 *     assistant when possible, else create one. This is the auto-hatch /
 *     first-run behavior — callers should leave `mode` unset for it.
 *   - `create`: provision an *additional* assistant (when multi-assistant
 *     hatching is enabled). Pass this to actually add a new one rather than
 *     get handed back the existing assistant.
 *
 * `status` distinguishes the outcome: 201 = newly created, 200 = an existing
 * assistant was returned (a `create` that the server deduped/declined).
 */
export async function hatchAssistant(
  input?: HatchInput,
  mode?: "create" | "ensure",
): Promise<HatchResult> {
  const { data, error, response } = await assistantsHatchCreate({
    body: input ?? {},
    query: mode ? { mode } : undefined,
    throwOnError: false,
  });

  assertHasResponse(response, error, "Failed to hatch assistant.");

  if (response.ok) {
    return {
      ok: true,
      status: response.status,
      data: data as Assistant,
    };
  }

  return {
    ok: false,
    status: response.status,
    error: toErrorObject(error, response),
  };
}

export async function getAssistant(
  assistantId?: string,
): Promise<GetAssistantResult> {
  if (isGatewayAuthMode()) {
    const lockfileAssistant = getSelectedAssistant();
    if (lockfileAssistant) {
      return {
        ok: true,
        status: 200,
        data: {
          id: lockfileAssistant.assistantId,
          name: lockfileAssistant.name ?? lockfileAssistant.assistantId,
          status: "active",
          is_local: true,
          created: lockfileAssistant.hatchedAt ?? "",
        } as Assistant,
      };
    }
  }
  if (assistantId) {
    const { data, error, response } = await assistantsRetrieve({
      path: { id: assistantId },
      throwOnError: false,
    });

    assertHasResponse(response, error, "Failed to get assistant.");

    if (response.ok) {
      return {
        ok: true,
        status: response.status,
        data: data as Assistant,
      };
    }

    return {
      ok: false,
      status: response.status,
      error: toErrorObject(error, response),
    };
  }

  // No ID provided — prefer platform-managed assistants, fall back to local.
  // Query platform first to avoid pagination issues with hosting=all.
  const platformResult = await assistantsList({
    query: { hosting: "platform" },
    throwOnError: false,
  });

  assertHasResponse(
    platformResult.response,
    platformResult.error,
    "Failed to get assistant.",
  );

  if (!platformResult.response.ok) {
    return {
      ok: false,
      status: platformResult.response.status,
      error: toErrorObject(platformResult.error, platformResult.response),
    };
  }

  const platformResults = platformResult.data?.results ?? [];
  if (platformResults.length > 0) {
    return {
      ok: true,
      status: platformResult.response.status,
      data: platformResults[0]!,
    };
  }

  // No platform assistant found — try local.
  const localResult = await assistantsList({
    query: { hosting: "local" },
    throwOnError: false,
  });

  assertHasResponse(
    localResult.response,
    localResult.error,
    "Failed to get assistant.",
  );

  if (localResult.response.ok) {
    const results = localResult.data?.results ?? [];
    if (results.length > 0) {
      return {
        ok: true,
        status: localResult.response.status,
        data: results[0]!,
      };
    }
  }

  if (!localResult.response.ok) {
    return {
      ok: false,
      status: localResult.response.status,
      error: toErrorObject(localResult.error, localResult.response),
    };
  }

  return {
    ok: false,
    status: 404,
    error: { detail: "No assistants found" },
  };
}

export async function getAssistantHealthz(
  assistantId: string,
): Promise<GetHealthzResult> {
  const { data, error, response } = await healthzGet({
    path: { assistant_id: assistantId },
    throwOnError: false,
  });

  assertHasResponse(response, error, "Failed to get assistant healthz.");

  if (response.ok && data) {
    return {
      ok: true,
      status: response.status,
      data,
    };
  }

  return {
    ok: false,
    status: response.status,
    error: toErrorObject(error, response),
  };
}

export async function getAssistantDiskPressureStatus(
  assistantId: string,
): Promise<GetAssistantDiskPressureStatusResult> {
  const { data, error, response } = await diskpressureStatusGet({
    path: { assistant_id: assistantId },
    throwOnError: false,
  });

  assertHasResponse(
    response,
    error,
    "Failed to get assistant disk pressure status.",
  );

  if (response.ok) {
    const parsed = DiskPressureStatusResponseSchema.safeParse(data);
    if (!parsed.success) {
      return {
        ok: false,
        status: response.status,
        error: toErrorObject(parsed.error.message, response),
      };
    }

    return {
      ok: true,
      status: response.status,
      data: parsed.data,
    };
  }

  return {
    ok: false,
    status: response.status,
    error: toErrorObject(error, response),
  };
}

export async function acknowledgeAssistantDiskPressure(
  assistantId: string,
): Promise<AcknowledgeAssistantDiskPressureResult> {
  const { data, error, response } = await diskpressureAcknowledgePost({
    path: { assistant_id: assistantId },
    throwOnError: false,
  });

  assertHasResponse(
    response,
    error,
    "Failed to acknowledge assistant disk pressure.",
  );

  if (response.ok) {
    const parsed = DiskPressureStatusResponseSchema.safeParse(data);
    if (!parsed.success) {
      return {
        ok: false,
        status: response.status,
        error: toErrorObject(parsed.error.message, response),
      };
    }

    return {
      ok: true,
      status: response.status,
      data: parsed.data,
    };
  }

  return {
    ok: false,
    status: response.status,
    error: toErrorObject(error, response),
  };
}

export interface AssistantBackup {
  snapshot_name: string;
  pvc: string;
  created_at: string;
  ready_to_use: boolean;
  backup_type: string;
  /** Full path to the snapshot file — used by daemon SDK restore. */
  path?: string;
}

export type ListBackupsResult =
  | { ok: true; status: number; data: AssistantBackup[] }
  | { ok: false; status: number; error: Record<string, unknown> };

interface DaemonSnapshot {
  path: string;
  filename: string;
  created_at: string;
  size_bytes: number;
  encrypted: boolean;
}

function parseDaemonBackups(
  data: unknown,
): AssistantBackup[] {
  const raw =
    data && typeof data === "object" && !Array.isArray(data)
      ? (data as Record<string, unknown>)
      : {};

  // Defensive: if the daemon SDK request fell through to Django
  // (platform-hosted, no gateway intercept) it returns
  // `{ backups: BackupItem[] }` instead of the daemon format.
  if (Array.isArray(raw.backups)) {
    return raw.backups as AssistantBackup[];
  }

  const body = raw as {
    local?: { snapshots?: DaemonSnapshot[] };
    offsite?: Array<{ snapshots?: DaemonSnapshot[] }>;
  };

  const snapshots: AssistantBackup[] = [];

  const localSnapshots = body.local?.snapshots;
  if (Array.isArray(localSnapshots)) {
    for (const s of localSnapshots) {
      snapshots.push({
        snapshot_name: s.filename,
        pvc: "",
        created_at: s.created_at,
        ready_to_use: true,
        backup_type: "scheduled",
        path: s.path,
      });
    }
  }

  if (Array.isArray(body.offsite)) {
    for (const dest of body.offsite) {
      if (Array.isArray(dest.snapshots)) {
        for (const s of dest.snapshots) {
          snapshots.push({
            snapshot_name: s.filename,
            pvc: "",
            created_at: s.created_at,
            ready_to_use: !s.encrypted,
            backup_type: "scheduled",
            path: s.path,
          });
        }
      }
    }
  }

  return snapshots;
}

function parsePlatformBackups(
  data: unknown,
): AssistantBackup[] {
  const raw =
    data && typeof data === "object" && !Array.isArray(data)
      ? (data as Record<string, unknown>)
      : {};

  if (Array.isArray(raw.backups)) {
    return raw.backups as AssistantBackup[];
  }

  return [];
}

export async function listAssistantBackups(
  assistantId: string,
): Promise<ListBackupsResult> {
  // For platform-hosted assistants the K8s PVC backups are managed by
  // the platform (vembda), not the daemon. Fetch both in parallel when
  // no self-hosted ingress is configured.
  const needsPlatform = !getSelfHostedIngressUrl();

  const [daemonResult, platformResult] = await Promise.all([
    backupsGet({
      path: { assistant_id: assistantId },
      throwOnError: false,
    }),
    needsPlatform
      ? assistantsBackupsRetrieve({
          path: { assistant_id: assistantId },
          throwOnError: false,
        })
      : null,
  ]);

  assertHasResponse(
    daemonResult.response,
    daemonResult.error,
    "Failed to list assistant backups.",
  );

  if (!daemonResult.response.ok) {
    return {
      ok: false,
      status: daemonResult.response.status,
      error: toErrorObject(daemonResult.error, daemonResult.response),
    };
  }

  const daemonSnapshots = parseDaemonBackups(daemonResult.data);

  if (platformResult) {
    if (platformResult.response?.ok) {
      const platformSnapshots = parsePlatformBackups(platformResult.data);
      return {
        ok: true,
        status: daemonResult.response.status,
        data: [...platformSnapshots, ...daemonSnapshots],
      };
    }

    // Platform call failed. If the daemon also returned nothing, surface
    // the platform error so the user doesn't see a silent empty list.
    if (daemonSnapshots.length === 0 && platformResult.response) {
      return {
        ok: false,
        status: platformResult.response.status,
        error: toErrorObject(platformResult.error, platformResult.response),
      };
    }
  }

  return { ok: true, status: daemonResult.response.status, data: daemonSnapshots };
}

export type CreateBackupResult =
  | { ok: true; status: number; data: Record<string, unknown> }
  | { ok: false; status: number; error: Record<string, unknown> };

export async function createAssistantBackup(
  assistantId: string,
): Promise<CreateBackupResult> {
  // When a self-hosted ingress URL is set, the daemon SDK client's
  // request interceptor rewrites the URL to the assistant's gateway
  // (skipSegmentAllowlist=true). The platform SDK client does NOT
  // rewrite "backups" paths, so we must use the daemon SDK for any
  // self-hosted assistant — whether accessed locally or via the
  // platform web app. For pure platform-hosted assistants (no ingress
  // URL), backup creation goes through Django → vembda.
  const { data, error, response } = getSelfHostedIngressUrl()
    ? await backupsCreatePost({
        path: { assistant_id: assistantId },
        throwOnError: false,
      })
    : await assistantsBackupsCreate({
        path: { assistant_id: assistantId },
        throwOnError: false,
      });

  assertHasResponse(response, error, "Failed to create assistant backup.");

  if (response.ok) {
    const body =
      data && typeof data === "object" && !Array.isArray(data)
        ? (data as Record<string, unknown>)
        : {};

    return { ok: true, status: response.status, data: body };
  }

  return {
    ok: false,
    status: response.status,
    error: toErrorObject(error, response),
  };
}

export type RestoreBackupResult =
  | { ok: true; status: number; data: Record<string, unknown> }
  | { ok: false; status: number; error: Record<string, unknown> };

export async function restoreAssistantBackup(
  assistantId: string,
  backup: AssistantBackup,
): Promise<RestoreBackupResult> {
  // Same routing split as createAssistantBackup.
  const { data, error, response } = getSelfHostedIngressUrl()
    ? await backupsRestorePost({
        path: { assistant_id: assistantId },
        body: { path: backup.path ?? backup.snapshot_name },
        throwOnError: false,
      })
    : await assistantsBackupsRestoreCreate({
        path: {
          assistant_id: assistantId,
          snapshot_name: backup.snapshot_name,
        },
        throwOnError: false,
      });

  assertHasResponse(response, error, "Failed to restore assistant backup.");

  if (response.ok) {
    const body =
      data && typeof data === "object" && !Array.isArray(data)
        ? (data as Record<string, unknown>)
        : {};

    return { ok: true, status: response.status, data: body };
  }

  return {
    ok: false,
    status: response.status,
    error: toErrorObject(error, response),
  };
}

export type RestartResult =
  | { ok: true; data: Record<string, unknown> }
  | { ok: false; status: number; error: Record<string, unknown> };

export async function restartAssistant(
  assistantId: string,
): Promise<RestartResult> {
  const { data, error, response } = await assistantsRestartDetailCreate({
    path: { id: assistantId },
    throwOnError: false,
  });

  assertHasResponse(response, error, "Failed to restart assistant.");

  if (response.ok) {
    const body =
      data && typeof data === "object" && !Array.isArray(data)
        ? (data as Record<string, unknown>)
        : {};

    return { ok: true, data: body };
  }

  return {
    ok: false,
    status: response.status,
    error: toErrorObject(error, response),
  };
}

export type RetireResult =
  | { ok: true }
  | { ok: false; status: number; error: Record<string, unknown> };

export async function retireAssistant(): Promise<RetireResult> {
  const { error, response } = await assistantsRetireDestroy({
    throwOnError: false,
  });

  assertHasResponse(response, error, "Failed to retire assistant.");

  if (response.ok) {
    return { ok: true };
  }

  return {
    ok: false,
    status: response.status,
    error: toErrorObject(error, response),
  };
}

export async function retireAssistantById(
  assistantId: string,
): Promise<RetireResult> {
  const { error, response } = await assistantsRetireDetailDestroy({
    path: { id: assistantId },
    throwOnError: false,
  });

  assertHasResponse(response, error, "Failed to retire assistant.");

  if (response.ok) {
    return { ok: true };
  }

  return {
    ok: false,
    status: response.status,
    error: toErrorObject(error, response),
  };
}

export type ListAssistantsResult =
  | { ok: true; status: number; data: Assistant[] }
  | { ok: false; status: number; error: Record<string, unknown> };

export async function listAssistants(): Promise<ListAssistantsResult> {
  const { data, error, response } = await assistantsList({
    query: { hosting: "all" },
    throwOnError: false,
  });

  assertHasResponse(response, error, "Failed to list assistants.");

  if (response.ok) {
    return {
      ok: true,
      status: response.status,
      data: data?.results ?? [],
    };
  }

  return {
    ok: false,
    status: response.status,
    error: toErrorObject(error, response),
  };
}

export type ActivateResult =
  | { ok: true; data: Assistant }
  | { ok: false; status: number; error: Record<string, unknown> };

export async function activateAssistant(
  assistantId: string,
): Promise<ActivateResult> {
  const { data, error, response } = await assistantsActivateCreate({
    path: { id: assistantId },
    throwOnError: false,
  });

  assertHasResponse(response, error, "Failed to activate assistant.");

  if (response.ok) {
    return { ok: true, data: data as Assistant };
  }

  return {
    ok: false,
    status: response.status,
    error: toErrorObject(error, response),
  };
}
