/**
 * A2A message envelope, content types, lifecycle event types, and
 * thread/conversation mapping for inter-assistant communication.
 *
 * These types define the wire contract for messages exchanged between
 * peer assistants over established A2A connections. Every message is
 * wrapped in an `A2AMessageEnvelope` that carries sender identity,
 * delivery metadata, and deduplication primitives.
 *
 * Lifecycle events formalize the notification signal event names already
 * emitted by `A2AConnectionService` (M8) into typed constants with
 * corresponding payload types.
 */

// ---------------------------------------------------------------------------
// Message status
// ---------------------------------------------------------------------------

/**
 * Delivery lifecycle for an A2A message.
 *   - `pending`   — queued for delivery, not yet sent
 *   - `delivered` — successfully delivered to the peer
 *   - `failed`    — delivery failed after exhausting retries
 */
export type A2AMessageStatus = 'pending' | 'delivered' | 'failed';

// ---------------------------------------------------------------------------
// Content types
// ---------------------------------------------------------------------------

/**
 * Plain text message content — the simplest content type.
 */
export interface A2ATextContent {
  type: 'text';
  text: string;
}

/**
 * Structured request — a typed action request from one assistant to another.
 * The `action` discriminator lets the receiver route to the right handler.
 * `params` is an arbitrary JSON-serializable payload specific to the action.
 */
export interface A2AStructuredRequest {
  type: 'structured_request';
  action: string;
  params: Record<string, unknown>;
}

/**
 * Structured response — the reply to a structured request, correlated by
 * `correlationId` in the envelope's delivery metadata.
 */
export interface A2AStructuredResponse {
  type: 'structured_response';
  action: string;
  result: Record<string, unknown>;
  success: boolean;
  error?: string;
}

/**
 * Union of all supported content types.
 */
export type A2AMessageContent =
  | A2ATextContent
  | A2AStructuredRequest
  | A2AStructuredResponse;

// ---------------------------------------------------------------------------
// Delivery metadata
// ---------------------------------------------------------------------------

/**
 * Metadata for message threading and request/response correlation.
 */
export interface A2ADeliveryMetadata {
  /**
   * Correlation ID linking a response to its originating request.
   * When sending a response, set this to the `messageId` of the
   * original request.
   */
  correlationId?: string;

  /**
   * Message ID of the message this is a reply to, enabling threaded
   * conversations between peers.
   */
  replyTo?: string;
}

// ---------------------------------------------------------------------------
// Message envelope
// ---------------------------------------------------------------------------

/**
 * The top-level wire format for all A2A messages.
 *
 * Every message is uniquely identified by `(connectionId, nonce)` for
 * deduplication. The nonce MUST be a cryptographically random UUID
 * generated by the sender.
 */
export interface A2AMessageEnvelope {
  /** Unique message identifier (UUID). */
  messageId: string;

  /** ID of the A2A connection this message belongs to. */
  connectionId: string;

  /** Sender's assistant ID (as known by the sender). */
  senderAssistantId: string;

  /** Cryptographic nonce for deduplication — unique per message. */
  nonce: string;

  /** Epoch milliseconds when the message was created. */
  timestamp: number;

  /** The message content (text, structured request, or structured response). */
  content: A2AMessageContent;

  /** Delivery metadata for threading and correlation. */
  delivery?: A2ADeliveryMetadata;

  /** Current delivery status. */
  status: A2AMessageStatus;
}

// ---------------------------------------------------------------------------
// Thread/conversation mapping
// ---------------------------------------------------------------------------

/**
 * Maps an A2A peer connection to a dedicated internal conversation.
 *
 * Each active peer connection gets its own conversation so that messages
 * from different peers are isolated. The `originMetadata` carries
 * attribution information for the peer.
 */
export interface A2AThreadMapping {
  /** The A2A connection ID. */
  connectionId: string;

  /** Internal conversation ID assigned to this peer connection. */
  conversationId: string;

  /** When the mapping was created (epoch ms). */
  createdAt: number;
}

/**
 * Origin metadata attached to a conversation that was created for an
 * A2A peer connection. Provides attribution context so the assistant
 * knows who it is talking to.
 */
export interface A2AOriginMetadata {
  /** The peer assistant's ID (if known). */
  peerAssistantId: string | null;

  /** The peer's guardian display name (if known). */
  peerGuardianDisplayName: string | null;

  /** The peer's gateway URL. */
  peerGatewayUrl: string;

  /** The A2A connection ID this conversation is bound to. */
  connectionId: string;
}

// ---------------------------------------------------------------------------
// Lifecycle event types
// ---------------------------------------------------------------------------

/**
 * All A2A lifecycle event name constants. These match the event names
 * already emitted by `A2AConnectionService` via `emitNotificationSignal()`.
 */
export const A2A_EVENT_NAMES = {
  CONNECTION_REQUESTED: 'a2a.connection_requested',
  CONNECTION_APPROVED: 'a2a.connection_approved',
  CONNECTION_DENIED: 'a2a.connection_denied',
  VERIFICATION_CODE_READY: 'a2a.verification_code_ready',
  CONNECTION_ESTABLISHED: 'a2a.connection_established',
  CONNECTION_REVOKED: 'a2a.connection_revoked',
  SCOPES_CHANGED: 'a2a.scopes_changed',
  MESSAGE_RECEIVED: 'a2a.message_received',
  MESSAGE_DELIVERED: 'a2a.message_delivered',
  MESSAGE_FAILED: 'a2a.message_failed',
} as const;

export type A2AEventName = (typeof A2A_EVENT_NAMES)[keyof typeof A2A_EVENT_NAMES];

// ---------------------------------------------------------------------------
// Lifecycle event payloads
// ---------------------------------------------------------------------------

/** Payload for `a2a.connection_requested`. */
export interface A2AConnectionRequestedPayload {
  connectionId: string;
  peerGatewayUrl: string;
  peerAssistantId: string | null;
  protocolVersion: string;
  capabilities: string[];
}

/** Payload for `a2a.connection_approved`. */
export interface A2AConnectionApprovedPayload {
  connectionId: string;
  peerGatewayUrl: string;
  peerAssistantId: string | null;
}

/** Payload for `a2a.connection_denied` (same shape as approved). */
export interface A2AConnectionDeniedPayload {
  connectionId: string;
  peerGatewayUrl: string;
  peerAssistantId: string | null;
}

/** Payload for `a2a.verification_code_ready`. */
export interface A2AVerificationCodeReadyPayload {
  connectionId: string;
  verificationCode: string;
  peerGatewayUrl: string;
  peerAssistantId: string | null;
}

/** Payload for `a2a.connection_established`. */
export interface A2AConnectionEstablishedPayload {
  connectionId: string;
  peerGatewayUrl: string;
  peerAssistantId: string | null;
  status: string;
}

/** Payload for `a2a.connection_revoked`. */
export interface A2AConnectionRevokedPayload {
  connectionId: string;
  peerGatewayUrl: string;
  peerAssistantId: string | null;
}

/** Payload for `a2a.scopes_changed`. */
export interface A2AScopesChangedPayload {
  connectionId: string;
  peerAssistantId: string | null;
  previousScopes: string[];
  newScopes: string[];
  timestamp: number;
}

/** Payload for `a2a.message_received`. */
export interface A2AMessageReceivedPayload {
  connectionId: string;
  messageId: string;
  senderAssistantId: string;
  contentType: A2AMessageContent['type'];
  conversationId?: string;
}

/** Payload for `a2a.message_delivered`. */
export interface A2AMessageDeliveredPayload {
  connectionId: string;
  messageId: string;
  recipientAssistantId?: string;
}

/** Payload for `a2a.message_failed`. */
export interface A2AMessageFailedPayload {
  connectionId: string;
  messageId: string;
  error: string;
}

// ---------------------------------------------------------------------------
// Event payload map — typed lookup by event name
// ---------------------------------------------------------------------------

/**
 * Maps each A2A event name to its typed payload. Allows type-safe
 * construction and consumption of lifecycle events.
 */
export interface A2AEventPayloadMap {
  'a2a.connection_requested': A2AConnectionRequestedPayload;
  'a2a.connection_approved': A2AConnectionApprovedPayload;
  'a2a.connection_denied': A2AConnectionDeniedPayload;
  'a2a.verification_code_ready': A2AVerificationCodeReadyPayload;
  'a2a.connection_established': A2AConnectionEstablishedPayload;
  'a2a.connection_revoked': A2AConnectionRevokedPayload;
  'a2a.scopes_changed': A2AScopesChangedPayload;
  'a2a.message_received': A2AMessageReceivedPayload;
  'a2a.message_delivered': A2AMessageDeliveredPayload;
  'a2a.message_failed': A2AMessageFailedPayload;
}

// ---------------------------------------------------------------------------
// Typed event construction helper
// ---------------------------------------------------------------------------

/**
 * A typed lifecycle event combining the event name with its payload.
 */
export interface A2ALifecycleEvent<T extends A2AEventName = A2AEventName> {
  eventName: T;
  payload: T extends keyof A2AEventPayloadMap ? A2AEventPayloadMap[T] : Record<string, unknown>;
  timestamp: number;
}

/**
 * Construct a typed lifecycle event. Type inference ensures the payload
 * matches the event name at compile time.
 */
export function createA2ALifecycleEvent<T extends A2AEventName>(
  eventName: T,
  payload: A2AEventPayloadMap[T],
  timestamp?: number,
): A2ALifecycleEvent<T> {
  return {
    eventName,
    payload,
    timestamp: timestamp ?? Date.now(),
  };
}

// ---------------------------------------------------------------------------
// Message construction helpers
// ---------------------------------------------------------------------------

/**
 * Create a text message envelope. Generates a unique messageId and nonce.
 */
export function createTextMessage(params: {
  connectionId: string;
  senderAssistantId: string;
  text: string;
  delivery?: A2ADeliveryMetadata;
  messageId?: string;
  nonce?: string;
  timestamp?: number;
}): A2AMessageEnvelope {
  const id = params.messageId ?? crypto.randomUUID();
  return {
    messageId: id,
    connectionId: params.connectionId,
    senderAssistantId: params.senderAssistantId,
    nonce: params.nonce ?? crypto.randomUUID(),
    timestamp: params.timestamp ?? Date.now(),
    content: { type: 'text', text: params.text },
    delivery: params.delivery,
    status: 'pending',
  };
}

/**
 * Create a structured request message envelope.
 */
export function createStructuredRequest(params: {
  connectionId: string;
  senderAssistantId: string;
  action: string;
  requestParams: Record<string, unknown>;
  delivery?: A2ADeliveryMetadata;
  messageId?: string;
  nonce?: string;
  timestamp?: number;
}): A2AMessageEnvelope {
  const id = params.messageId ?? crypto.randomUUID();
  return {
    messageId: id,
    connectionId: params.connectionId,
    senderAssistantId: params.senderAssistantId,
    nonce: params.nonce ?? crypto.randomUUID(),
    timestamp: params.timestamp ?? Date.now(),
    content: {
      type: 'structured_request',
      action: params.action,
      params: params.requestParams,
    },
    delivery: params.delivery,
    status: 'pending',
  };
}

/**
 * Create a structured response message envelope.
 */
export function createStructuredResponse(params: {
  connectionId: string;
  senderAssistantId: string;
  action: string;
  result: Record<string, unknown>;
  success: boolean;
  error?: string;
  correlationId: string;
  delivery?: Omit<A2ADeliveryMetadata, 'correlationId'>;
  messageId?: string;
  nonce?: string;
  timestamp?: number;
}): A2AMessageEnvelope {
  const id = params.messageId ?? crypto.randomUUID();
  return {
    messageId: id,
    connectionId: params.connectionId,
    senderAssistantId: params.senderAssistantId,
    nonce: params.nonce ?? crypto.randomUUID(),
    timestamp: params.timestamp ?? Date.now(),
    content: {
      type: 'structured_response',
      action: params.action,
      result: params.result,
      success: params.success,
      error: params.error,
    },
    delivery: {
      ...params.delivery,
      correlationId: params.correlationId,
    },
    status: 'pending',
  };
}
