// Re-export all conversation store functionality from focused sub-modules.
// Existing imports from this file continue to work without changes.

export {
  addMessage,
  batchSetDisplayOrders,
  clearAll,
  type ConversationRow,
  createConversation,
  deleteConversation,
  type DeletedMemoryIds,
  deleteLastExchange,
  deleteMessageById,
  getConversation,
  getConversationMemoryScopeId,
  getConversationOriginChannel,
  getConversationOriginInterface,
  getConversationRecentProvenanceTrustClass,
  getConversationThreadType,
  getDisplayMetaForConversations,
  getMessageById,
  getMessages,
  type MessageMetadata,
  messageMetadataSchema,
  type MessageRow,
  parseConversation,
  parseMessage,
  provenanceFromTrustContext,
  relinkAttachments,
  setConversationOriginChannelIfUnset,
  setConversationOriginInterfaceIfUnset,
  updateConversationContextWindow,
  updateConversationTitle,
  updateConversationUsage,
  updateMessageContent,
} from "./conversation-crud.js";
export {
  type ConversationSearchResult,
  countConversations,
  getLatestConversation,
  getMessagesPaginated,
  getNextMessage,
  isLastUserMessageToolResult,
  listConversations,
  type PaginatedMessagesResult,
  searchConversations,
} from "./conversation-queries.js";
