// Re-export all conversation store functionality from focused sub-modules.
// Existing imports from this file continue to work without changes.

export {
  messageMetadataSchema,
  type MessageMetadata,
  provenanceFromGuardianContext,
  type ConversationRow,
  parseConversation,
  type MessageRow,
  parseMessage,
  createConversation,
  getConversation,
  getConversationThreadType,
  getConversationMemoryScopeId,
  deleteConversation,
  addMessage,
  getMessages,
  getMessageById,
  updateConversationTitle,
  updateConversationUsage,
  updateConversationContextWindow,
  clearAll,
  deleteLastExchange,
  type DeletedMemoryIds,
  updateMessageContent,
  relinkAttachments,
  deleteMessageById,
  setConversationOriginChannelIfUnset,
  getConversationOriginChannel,
  setConversationOriginInterfaceIfUnset,
  getConversationOriginInterface,
} from './conversation-crud.js';

export {
  listConversations,
  countConversations,
  getLatestConversation,
  getNextMessage,
  type PaginatedMessagesResult,
  getMessagesPaginated,
  isLastUserMessageToolResult,
  type ConversationSearchResult,
  searchConversations,
} from './conversation-queries.js';
