// Re-export all migrations from individual files for backward compatibility.
export {
  migrateAddOriginInterface,
  migrateAssistantIdToSelf,
  migrateBackfillInboxThreadStateFromBindings,
  migrateCallSessionsAddInitiatedFrom,
  migrateCallSessionsProviderSidDedup,
  migrateDropActiveSearchIndex,
  migrateEmbeddingVectorBlob,
  migrateExtConvBindingsChannelChatUnique,
  migrateGuardianActionTables,
  migrateJobDeferrals,
  migrateLlmUsageEventsDropAssistantId,
  migrateMemoryEntityRelationDedup,
  migrateMemoryFtsBackfill,
  migrateMemoryItemsFingerprintScopeUnique,
  migrateMemoryItemsIndexes,
  migrateMemoryItemSourcesIndexes,
  migrateMemoryItemsScopeSaltedFingerprints,
  migrateMemorySegmentsIndexes,
  migrateNotificationTablesSchema,
  migrateRemainingTableIndexes,
  migrateRemoveAssistantIdColumns,
  migrateToolInvocationsFk,
  MIGRATION_REGISTRY,
  type MigrationRegistryEntry,
  type MigrationValidationResult,
  validateMigrationState,
} from './migrations/index.js';
