// Re-export all migrations from individual files for backward compatibility.
export {
  type MigrationRegistryEntry,
  MIGRATION_REGISTRY,
  type MigrationValidationResult,
  validateMigrationState,
  migrateJobDeferrals,
  migrateToolInvocationsFk,
  migrateMemoryFtsBackfill,
  migrateMemoryEntityRelationDedup,
  migrateMemoryItemsFingerprintScopeUnique,
  migrateMemoryItemsScopeSaltedFingerprints,
  migrateAssistantIdToSelf,
  migrateRemoveAssistantIdColumns,
  migrateLlmUsageEventsDropAssistantId,
  migrateExtConvBindingsChannelChatUnique,
  migrateCallSessionsProviderSidDedup,
  migrateCallSessionsAddInitiatedFrom,
  migrateGuardianActionTables,
  migrateBackfillInboxThreadStateFromBindings,
  migrateDropActiveSearchIndex,
} from './migrations/index.js';
