// Re-export all migrations from individual files for backward compatibility.
export {
  migrateAddOriginInterface,
  migrateAssistantIdToSelf,
  migrateBackfillInboxThreadStateFromBindings,
  migrateCallSessionsAddInitiatedFrom,
  migrateCallSessionsProviderSidDedup,
  migrateDropActiveSearchIndex,
  migrateEmbeddingVectorBlob,
  migrateExtConvBindingsChannelChatUnique,
  migrateGuardianActionTables,
  migrateJobDeferrals,
  migrateLlmUsageEventsDropAssistantId,
  migrateMemoryEntityRelationDedup,
  migrateMemoryFtsBackfill,
  migrateMemoryItemsFingerprintScopeUnique,
  migrateMemoryItemsIndexes,
  migrateMemoryItemSourcesIndexes,
  migrateMemoryItemsScopeSaltedFingerprints,
  migrateMemorySegmentsIndexes,
  migrateMessagesFtsBackfill,
  migrateNormalizePhoneIdentities,
  migrateNotificationDeliveryPairingColumns,
  migrateNotificationDeliveryThreadDecision,
  migrateNotificationTablesSchema,
  migrateRemainingTableIndexes,
  migrateReminderRoutingIntent,
  migrateRemoveAssistantIdColumns,
  migrateSchemaIndexesAndColumns,
  migrateToolInvocationsFk,
  migrateUsageDashboardIndexes,
  MIGRATION_REGISTRY,
  type MigrationRegistryEntry,
  type MigrationValidationResult,
  recoverCrashedMigrations,
  validateMigrationState,
  withCrashRecovery,
} from "./migrations/index.js";
