/**
 * Tiny client-side heuristics for username UX. Intentionally separate so
 * the regex is unit-testable without dragging in the React component.
 */

/**
 * Detects handles that look like they came from allauth's
 * ``generate_unique_username`` (e.g. ``alice17``, ``user_42``).
 *
 * The heuristic is a false-positive-tolerant trigger for a softer
 * onboarding nudge ("claim one you like") — never a hard signal. We
 * intentionally avoid relying on it for any save-path decision.
 */
export function looksAutoGenerated(username: string): boolean {
  return /\d{2,}$/.test(username);
}
