/**
 * App icon registry: the icons an app can wear in the sidebar, the library
 * and the chat's app tiles, keyed by the Lucide kebab-case name the daemon
 * stores on the app's manifest (`app.icon`).
 *
 * Mirrors the custom-group registry (`@/domains/chat/utils/group-icon-registry`):
 * map a stored name to a module-level Lucide component once, and every
 * surface resolves through it. The assistant picks the name at `app_create`
 * from the same list, which lives on its side in
 * `assistant/src/apps/app-icons.ts`; the two lists are kept identical by
 * hand, and a name this registry does not know falls back to
 * {@link DEFAULT_APP_ICON} rather than to a broken glyph.
 *
 * Apps built before the switch carry an emoji instead. The common ones are
 * bridged to the registry name they stood for, so an existing library does
 * not turn into a wall of rockets; the rest take the default glyph.
 */

import { createElement } from "react";

import {
  Activity,
  AlarmClock,
  Apple,
  Baby,
  Battery,
  Bed,
  Beer,
  Bell,
  Bike,
  Book,
  BookOpen,
  Bookmark,
  Bot,
  Brain,
  Briefcase,
  Bus,
  Cake,
  Calculator,
  Calendar,
  Camera,
  Car,
  Carrot,
  ChartBar,
  ChartLine,
  ChartPie,
  ClipboardList,
  Clock,
  Cloud,
  Code,
  Coffee,
  Compass,
  Contact,
  Cpu,
  CreditCard,
  Database,
  DollarSign,
  Droplets,
  Dumbbell,
  Egg,
  FileText,
  Film,
  Fish,
  Flag,
  Flame,
  FolderOpen,
  Gamepad2,
  Gauge,
  Gift,
  Globe,
  GraduationCap,
  Hash,
  Headphones,
  Heart,
  HeartPulse,
  House,
  Image,
  Inbox,
  Key,
  Languages,
  Layers,
  Leaf,
  Lightbulb,
  Link,
  ListChecks,
  ListTodo,
  Lock,
  Mail,
  Map,
  MapPin,
  MessageSquare,
  Mic,
  Moon,
  Mountain,
  Music,
  Newspaper,
  NotebookPen,
  Package,
  Palette,
  PartyPopper,
  PawPrint,
  PenTool,
  Pencil,
  Percent,
  Phone,
  PiggyBank,
  Pill,
  Plane,
  Play,
  Plug,
  Puzzle,
  Receipt,
  Repeat,
  Rocket,
  Ruler,
  Salad,
  Scale,
  Scissors,
  Search,
  Settings,
  Shield,
  Ship,
  Shirt,
  ShoppingCart,
  Shuffle,
  Smile,
  Snowflake,
  Sparkles,
  Speaker,
  SquareCheck,
  SquareKanban,
  Star,
  Stethoscope,
  StickyNote,
  Sun,
  Table,
  Target,
  Terminal,
  Thermometer,
  Ticket,
  Timer,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  Users,
  Utensils,
  Video,
  Volume2,
  Wallet,
  Wifi,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";

const APP_ICONS: Record<string, LucideIcon> = {
  calculator: Calculator,
  calendar: Calendar,
  "list-todo": ListTodo,
  "list-checks": ListChecks,
  "square-check": SquareCheck,
  timer: Timer,
  clock: Clock,
  "alarm-clock": AlarmClock,
  "notebook-pen": NotebookPen,
  "sticky-note": StickyNote,
  pencil: Pencil,
  "file-text": FileText,
  "clipboard-list": ClipboardList,
  bookmark: Bookmark,
  book: Book,
  "book-open": BookOpen,
  "chart-bar": ChartBar,
  "chart-line": ChartLine,
  "chart-pie": ChartPie,
  table: Table,
  "square-kanban": SquareKanban,
  database: Database,
  gauge: Gauge,
  activity: Activity,
  target: Target,
  flag: Flag,
  trophy: Trophy,
  wallet: Wallet,
  "dollar-sign": DollarSign,
  "piggy-bank": PiggyBank,
  "credit-card": CreditCard,
  receipt: Receipt,
  percent: Percent,
  "shopping-cart": ShoppingCart,
  package: Package,
  gift: Gift,
  ticket: Ticket,
  mail: Mail,
  inbox: Inbox,
  "message-square": MessageSquare,
  phone: Phone,
  bell: Bell,
  users: Users,
  contact: Contact,
  music: Music,
  headphones: Headphones,
  mic: Mic,
  video: Video,
  film: Film,
  tv: Tv,
  play: Play,
  image: Image,
  camera: Camera,
  "gamepad-2": Gamepad2,
  puzzle: Puzzle,
  "party-popper": PartyPopper,
  smile: Smile,
  map: Map,
  "map-pin": MapPin,
  compass: Compass,
  globe: Globe,
  plane: Plane,
  car: Car,
  bus: Bus,
  bike: Bike,
  ship: Ship,
  truck: Truck,
  house: House,
  bed: Bed,
  briefcase: Briefcase,
  "graduation-cap": GraduationCap,
  languages: Languages,
  brain: Brain,
  lightbulb: Lightbulb,
  heart: Heart,
  "heart-pulse": HeartPulse,
  dumbbell: Dumbbell,
  pill: Pill,
  stethoscope: Stethoscope,
  baby: Baby,
  "paw-print": PawPrint,
  utensils: Utensils,
  coffee: Coffee,
  wine: Wine,
  beer: Beer,
  cake: Cake,
  apple: Apple,
  carrot: Carrot,
  salad: Salad,
  egg: Egg,
  fish: Fish,
  cloud: Cloud,
  sun: Sun,
  moon: Moon,
  umbrella: Umbrella,
  snowflake: Snowflake,
  thermometer: Thermometer,
  droplets: Droplets,
  flame: Flame,
  leaf: Leaf,
  mountain: Mountain,
  code: Code,
  terminal: Terminal,
  cpu: Cpu,
  bot: Bot,
  wifi: Wifi,
  lock: Lock,
  key: Key,
  shield: Shield,
  settings: Settings,
  wrench: Wrench,
  plug: Plug,
  battery: Battery,
  search: Search,
  link: Link,
  hash: Hash,
  layers: Layers,
  "folder-open": FolderOpen,
  palette: Palette,
  "pen-tool": PenTool,
  ruler: Ruler,
  scale: Scale,
  scissors: Scissors,
  shirt: Shirt,
  newspaper: Newspaper,
  repeat: Repeat,
  shuffle: Shuffle,
  "volume-2": Volume2,
  speaker: Speaker,
  star: Star,
  sparkles: Sparkles,
  zap: Zap,
  rocket: Rocket,
  /* Lucide's older name for `house`, in case a model reaches for it. */
  home: House,
};

/** The names the assistant may choose from, in registry order. */
export const APP_ICON_NAMES: readonly string[] = Object.keys(APP_ICONS);

/** The glyph for an app with no icon, or one whose name is unknown here. */
export const DEFAULT_APP_ICON: LucideIcon = Rocket;

/**
 * The emoji apps carried before the registry, each bridged to the registry
 * name it stood for. The daemon applies the same bridge when it reads a
 * manifest (`assistant/src/apps/app-icons.ts`); this copy covers a daemon
 * older than that, so an existing library wears the glyph set either way.
 * Keys carry no variation selector; the lookup strips it.
 */
const LEGACY_EMOJI_ICONS: Record<string, string> = {
  "🔢": "calculator",
  "🧮": "calculator",
  "📅": "calendar",
  "🗓": "calendar",
  "✅": "list-todo",
  "☑": "list-checks",
  "⏱": "timer",
  "⏲": "timer",
  "⏰": "alarm-clock",
  "🕐": "clock",
  "🕒": "clock",
  "📝": "notebook-pen",
  "🗒": "sticky-note",
  "✏": "pencil",
  "📄": "file-text",
  "📋": "clipboard-list",
  "🔖": "bookmark",
  "📚": "book",
  "📖": "book-open",
  "📔": "notebook-pen",
  "📊": "chart-bar",
  "📈": "chart-line",
  "📉": "chart-line",
  "🥧": "chart-pie",
  "🗄": "database",
  "🎯": "target",
  "🚩": "flag",
  "🏆": "trophy",
  "🏁": "flag",
  "💰": "wallet",
  "💵": "dollar-sign",
  "💲": "dollar-sign",
  "🐷": "piggy-bank",
  "💳": "credit-card",
  "🧾": "receipt",
  "🛒": "shopping-cart",
  "🛍": "shopping-cart",
  "📦": "package",
  "🎁": "gift",
  "🎟": "ticket",
  "🎫": "ticket",
  "✉": "mail",
  "📧": "mail",
  "📨": "mail",
  "📥": "inbox",
  "💬": "message-square",
  "🗨": "message-square",
  "📞": "phone",
  "☎": "phone",
  "🔔": "bell",
  "👥": "users",
  "👤": "contact",
  "🎵": "music",
  "🎶": "music",
  "🎧": "headphones",
  "🎤": "mic",
  "🎙": "mic",
  "📹": "video",
  "🎬": "film",
  "🎥": "film",
  "📺": "tv",
  "▶": "play",
  "🖼": "image",
  "📷": "camera",
  "📸": "camera",
  "🎮": "gamepad-2",
  "🕹": "gamepad-2",
  "🧩": "puzzle",
  "🎉": "party-popper",
  "🎊": "party-popper",
  "😀": "smile",
  "🙂": "smile",
  "🗺": "map",
  "📍": "map-pin",
  "🧭": "compass",
  "🌍": "globe",
  "🌎": "globe",
  "🌏": "globe",
  "✈": "plane",
  "🚗": "car",
  "🚌": "bus",
  "🚲": "bike",
  "🚢": "ship",
  "🚚": "truck",
  "🏠": "house",
  "🏡": "house",
  "🛏": "bed",
  "💼": "briefcase",
  "🎓": "graduation-cap",
  "🌐": "languages",
  "🧠": "brain",
  "💡": "lightbulb",
  "❤": "heart",
  "💗": "heart-pulse",
  "🏋": "dumbbell",
  "💪": "dumbbell",
  "💊": "pill",
  "🩺": "stethoscope",
  "👶": "baby",
  "🐾": "paw-print",
  "🐶": "paw-print",
  "🐱": "paw-print",
  "🍽": "utensils",
  "🍴": "utensils",
  "☕": "coffee",
  "🍷": "wine",
  "🍺": "beer",
  "🍰": "cake",
  "🎂": "cake",
  "🍎": "apple",
  "🥕": "carrot",
  "🥗": "salad",
  "🥚": "egg",
  "🐟": "fish",
  "☁": "cloud",
  "🌤": "cloud",
  "☀": "sun",
  "🌞": "sun",
  "🌙": "moon",
  "☂": "umbrella",
  "🌧": "umbrella",
  "❄": "snowflake",
  "🌡": "thermometer",
  "💧": "droplets",
  "🔥": "flame",
  "🌱": "leaf",
  "🍃": "leaf",
  "🏔": "mountain",
  "⛰": "mountain",
  "💻": "code",
  "👨‍💻": "code",
  "🖥": "terminal",
  "⌨": "terminal",
  "🤖": "bot",
  "📡": "wifi",
  "🔒": "lock",
  "🔐": "lock",
  "🔑": "key",
  "🛡": "shield",
  "⚙": "settings",
  "🔧": "wrench",
  "🛠": "wrench",
  "🔌": "plug",
  "🔋": "battery",
  "🔍": "search",
  "🔎": "search",
  "🔗": "link",
  "#️⃣": "hash",
  "📁": "folder-open",
  "📂": "folder-open",
  "🎨": "palette",
  "🖌": "pen-tool",
  "📏": "ruler",
  "⚖": "scale",
  "✂": "scissors",
  "👕": "shirt",
  "📰": "newspaper",
  "🔁": "repeat",
  "🔀": "shuffle",
  "🔊": "volume-2",
  "⭐": "star",
  "🌟": "star",
  "✨": "sparkles",
  "⚡": "zap",
  "🚀": "rocket",
};

const VARIATION_SELECTORS = /[\uFE0E\uFE0F]/gu;

function iconByName(name: string): LucideIcon | undefined {
  /* `hasOwn` rather than a bare index: an indexed read of a `Record` is typed
     as never missing, and it would also find `constructor` on the prototype. */
  return Object.hasOwn(APP_ICONS, name) ? APP_ICONS[name] : undefined;
}

/**
 * The Lucide component for an app's stored icon: a registry name (any
 * case), or a pre-registry emoji the bridge knows. `undefined` for nothing
 * usable (absent, an unknown name, an emoji the bridge does not know, a
 * stray URL); callers that must draw something use {@link DEFAULT_APP_ICON}
 * or their own placeholder. Never the emoji itself: an app wears the
 * product's glyph set or the fallback, not a platform's emoji font.
 */
export function getAppIcon(
  icon: string | null | undefined,
): LucideIcon | undefined {
  if (!icon) {
    return undefined;
  }
  const trimmed = icon.trim();
  const byName = iconByName(trimmed.toLowerCase());
  if (byName) {
    return byName;
  }
  const bridged = Object.hasOwn(
    LEGACY_EMOJI_ICONS,
    trimmed.replace(VARIATION_SELECTORS, ""),
  )
    ? LEGACY_EMOJI_ICONS[trimmed.replace(VARIATION_SELECTORS, "")]
    : undefined;
  return bridged ? iconByName(bridged) : undefined;
}

export interface AppIconProps extends LucideProps {
  /** The app's stored icon (`app.icon`). */
  icon: string | null | undefined;
  /** Drawn when the registry cannot place the icon. */
  fallback?: LucideIcon;
}

/**
 * An app's icon as an element: the registry glyph for `icon`, else
 * `fallback` (the {@link DEFAULT_APP_ICON} unless told otherwise). A
 * component rather than a resolved constructor rendered at the call site,
 * which React's static-components rule reads as a component made during
 * render.
 */
export function AppIcon({
  icon,
  fallback = DEFAULT_APP_ICON,
  ...props
}: AppIconProps) {
  return createElement(getAppIcon(icon) ?? fallback, props);
}
