/**
 * Unit tests for the no-barrel-files ESLint rule.
 *
 * Run with: `bun test eslint-rules/no-barrel-files.test.mjs`
 */
import path from "node:path";
import { fileURLToPath } from "node:url";
import { RuleTester } from "eslint";

import { noBarrelFiles } from "./no-barrel-files.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const WEB_ROOT = path.resolve(__dirname, "..");

const ruleTester = new RuleTester({
  languageOptions: {
    ecmaVersion: "latest",
    sourceType: "module",
  },
});

ruleTester.run("no-barrel-files", noBarrelFiles, {
  valid: [
    // Non-index files are always fine.
    {
      filename: path.join(WEB_ROOT, "src", "domains", "chat", "chat-page.tsx"),
      code: `export const x = 1;`,
    },
    // index.ts under generated/ is allowed (autogenerated barrel).
    {
      filename: path.join(WEB_ROOT, "src", "generated", "api", "index.ts"),
      code: `export * from "./types.gen.js";`,
    },
    // Nested generated paths still exempt.
    {
      filename: path.join(
        WEB_ROOT,
        "src",
        "generated",
        "daemon",
        "index.tsx",
      ),
      code: `export * from "./types.gen.js";`,
    },
  ],
  invalid: [
    {
      filename: path.join(WEB_ROOT, "src", "domains", "chat", "index.ts"),
      code: `export * from "./chat-page.js";`,
      errors: [{ messageId: "barrel" }],
    },
    {
      filename: path.join(WEB_ROOT, "src", "hooks", "index.tsx"),
      code: `export { useIsMobile } from "./use-is-mobile.js";`,
      errors: [{ messageId: "barrel" }],
    },
  ],
});
