// ---------------------------------------------------------------------------
// Memory v2 — Shared types
// ---------------------------------------------------------------------------
//
// Zod schemas (and inferred TypeScript types) shared across the v2 memory
// subsystem. Each value here crosses a serialization boundary — YAML
// frontmatter, on-disk JSON, or a SQLite JSON column — so runtime validation
// is needed wherever it is read.
//
// This file must not import from any other `memory/v2/*` module — it is the
// leaf of the v2 dependency graph.

import { z } from "zod";

// ---------------------------------------------------------------------------
// Concept pages
// ---------------------------------------------------------------------------

/**
 * YAML frontmatter at the top of a concept page (`memory/concepts/<slug>.md`).
 *
 * `edges` is a derived view of `memory/edges.json` — it is regenerated by
 * the rebuild-edges backfill job and is not the source of truth for the graph
 * topology. `ref_files` lists paths to attached media (images, audio, etc.).
 */
export const ConceptPageFrontmatterSchema = z.object({
  edges: z.array(z.string()).default([]),
  ref_files: z.array(z.string()).default([]),
});

export type ConceptPageFrontmatter = z.infer<
  typeof ConceptPageFrontmatterSchema
>;

/**
 * A single concept page on disk. The slug is the filename minus `.md` and
 * also the stable identity used in edges and activation state.
 */
export const ConceptPageSchema = z.object({
  slug: z.string(),
  frontmatter: ConceptPageFrontmatterSchema,
  body: z.string(),
});

export type ConceptPage = z.infer<typeof ConceptPageSchema>;

// ---------------------------------------------------------------------------
// Edges index (`memory/edges.json`)
// ---------------------------------------------------------------------------

/**
 * Source of truth for v2 graph topology. Edges are unweighted, undirected,
 * and stored as canonicalized 2-tuples (alphabetical-first slug first).
 */
export const EdgesIndexSchema = z.object({
  version: z.literal(1),
  edges: z.array(z.tuple([z.string(), z.string()])),
});

export type EdgesIndex = z.infer<typeof EdgesIndexSchema>;

// ---------------------------------------------------------------------------
// Activation state (per-conversation, persisted in SQLite)
// ---------------------------------------------------------------------------

/**
 * One entry in the per-conversation `everInjected` list. Tracks which
 * concept-page slug was injected on which turn so compaction can selectively
 * evict slugs whose attachments lived on compacted turns.
 */
export const EverInjectedEntrySchema = z.object({
  slug: z.string(),
  turn: z.number().int().nonnegative(),
});

export type EverInjectedEntry = z.infer<typeof EverInjectedEntrySchema>;

/**
 * Snapshot of memory v2 retrieval state for a single conversation.
 *
 * `state` is a sparse map of slug → activation in [0, 1]; only slugs above
 * `epsilon` are persisted. `everInjected` is the running list of slugs the
 * assistant has already attached to a user message, used to make injection
 * append-only and cache-stable.
 */
export const ActivationStateSchema = z.object({
  messageId: z.string(),
  state: z.record(z.string(), z.number()),
  everInjected: z.array(EverInjectedEntrySchema),
  currentTurn: z.number().int().nonnegative(),
  updatedAt: z.number().int().nonnegative(),
});

export type ActivationState = z.infer<typeof ActivationStateSchema>;

// ---------------------------------------------------------------------------
// Skill autoinjection (synthetic in-memory entries, not on-disk pages)
// ---------------------------------------------------------------------------

/**
 * Per-skill capability snapshot held in-process and embedded into
 * the `memory_v2_skills` Qdrant collection. `content` is the rendered
 * `buildSkillContent` string — already capped at 500 chars upstream — and
 * is what we embed and what we render in `### Skills You Can Use`.
 */
export const SkillEntrySchema = z.object({
  id: z.string(),
  displayName: z.string(),
  content: z.string(),
});

export type SkillEntry = z.infer<typeof SkillEntrySchema>;

/**
 * Payload carried alongside each `memory_v2_skills` Qdrant point. Mirrors
 * the `ConceptPagePayload` shape but keyed on `id` instead of `slug`.
 */
export const SkillEmbeddingPayloadSchema = z.object({
  id: z.string(),
  displayName: z.string(),
  content: z.string(),
  updated_at: z.number().int().nonnegative(),
});

export type SkillEmbeddingPayload = z.infer<typeof SkillEmbeddingPayloadSchema>;
