import { readFile } from "node:fs/promises";
import { join } from "node:path";

import { SITE_URL } from "@/lib/metadata";

/**
 * Serves agent-facing Markdown mirrors generated by
 * scripts/generate-agent-markdown.ts into generated/md/.
 *
 * The folder name %5Fmd is the URL-encoded form of _md: a folder literally
 * named _md would be a private folder that the app router excludes from
 * routing, while %5Fmd registers the route as /docs/_md.
 *
 * Agents reach this handler two ways, both defined in next.config.ts:
 * - The `.md` URL-suffix rewrites map the canonical page URL plus a `.md`
 *   suffix here (/docs/index.md for the docs index, /docs/<path>.md for every
 *   other page). Unlike content negotiation, this works for crawlers that
 *   never send an Accept: text/markdown header.
 * - The Accept: text/markdown rewrites map eligible /docs pages here while
 *   browsers continue to receive HTML at the same URL.
 */

const MARKDOWN_ROOT = join(process.cwd(), "generated", "md");
const SEGMENT_PATTERN = /^[a-z0-9-]+$/;

function markdownResponse(markdown: string, canonicalUrl: string): Response {
  return new Response(markdown, {
    status: 200,
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      // The same URL never serves HTML, but the rewritten page URLs do;
      // Vary keeps CDN cache entries for the two representations separate.
      Vary: "Accept",
      Link: `<${canonicalUrl}>; rel="canonical"`,
      "Cache-Control": "public, s-maxage=3600, stale-while-revalidate=86400",
    },
  });
}

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ slug?: string[] }> }
): Promise<Response> {
  const { slug = [] } = await params;

  if (!slug.every((segment) => SEGMENT_PATTERN.test(segment))) {
    return new Response("Not found", { status: 404 });
  }

  // An empty slug is the docs index (/docs), mirrored at generated/md/docs.md.
  const docsPath = ["docs", ...slug].join("/");

  let markdown: string;
  try {
    markdown = await readFile(join(MARKDOWN_ROOT, `${docsPath}.md`), "utf8");
  } catch {
    return new Response("Not found", { status: 404 });
  }

  return markdownResponse(markdown, `${SITE_URL}/${docsPath}`);
}
