/**
 * Daemon config helpers.
 *
 * Query and mutation hooks are generated by HeyAPI — use `useConfigGetQuery`,
 * `useConfigPatchMutation`, and `configGetSetQueryData` from
 * `@/generated/daemon/@tanstack/react-query.gen` directly.
 *
 * This file only exports `useProvisionProviderKey`, which composes the
 * generated `secretsPost` SDK function with error handling and toasts.
 */

import { useCallback } from "react";

import { useActiveAssistantId } from "@/assistant/use-active-assistant-id";
import { assertProvisionSuccess } from "@/domains/settings/ai/utils";
import { secretsPost } from "@/generated/daemon/sdk.gen";
import { captureError } from "@/lib/sentry/capture-error";
import { toast } from "@vellumai/design-library/components/toast";

// ---------------------------------------------------------------------------
// useProvisionProviderKey — API key provisioning
// ---------------------------------------------------------------------------

/**
 * Hook for provisioning provider API keys on the daemon.
 *
 * Used by web-search-card and image-generation-card to store BYOK
 * credentials. Returns a stable callback.
 */
export function useProvisionProviderKey() {
  const assistantId = useActiveAssistantId();

  return useCallback(
    async (providerName: string, key: string): Promise<void> => {
      try {
        const { data } = await secretsPost({
          path: { assistant_id: assistantId },
          body: { value: key, type: "api_key", name: providerName },
          throwOnError: true,
        });
        assertProvisionSuccess(data);
      } catch (error) {
        if (error instanceof Error && error.message === "No assistant found") {
          toast.error("Assistant not ready. Please try again.");
        } else {
          toast.error(`Failed to save ${providerName} API key. Please try again.`);
        }
        captureError(error, { context: "provision_provider_key" });
        throw error;
      }
    },
    [assistantId],
  );
}
