import SwiftUI
import VellumAssistantShared

/// Namespaced identifier for the Reflections sidebar section. Used as a key
/// into `SidebarInteractionState.expandedSections` and `showAllInSection`
/// so its state persists between launches alongside other system groups.
/// The `"system:"` prefix matches the convention used by `ConversationGroup`
/// (e.g. `system:pinned`, `system:all`) even though reflections aren't a
/// real conversation group — they're a derived view.
enum ReflectionsSidebarSectionId {
    static let id = "system:reflections"
}

/// Sidebar section that surfaces auto-analysis ("reflection") conversations
/// separately from the user's regular conversations. Rendered beneath the
/// main conversation groups when at least one auto-analysis conversation
/// exists — hidden entirely when the list is empty.
///
/// Kept intentionally minimal: no drag/drop, sub-groups, rename, delete,
/// or archive-all affordances. Reflections are generated by the system,
/// not organised by the user.
struct SidebarReflectionsSection: View {
    let conversations: [ConversationModel]
    let isExpanded: Bool
    let showAll: Bool
    let maxCollapsed: Int
    let selectedConversationId: UUID?
    var onToggleExpand: () -> Void
    var onToggleShowAll: () -> Void
    var makeRow: (ConversationModel) -> SidebarConversationItem

    @State private var isHeaderHovered: Bool = false

    private var hasUnread: Bool {
        conversations.contains(where: \.hasUnseenLatestAssistantMessage)
    }

    private var displayedConversations: [ConversationModel] {
        if showAll { return conversations }
        return Array(conversations.prefix(maxCollapsed))
    }

    var body: some View {
        header

        if isExpanded && !conversations.isEmpty {
            VStack(spacing: 0) {
                ForEach(displayedConversations) { conversation in
                    makeRow(conversation)
                        .equatable()
                        .id(ConversationRowIdentity(conversationId: conversation.id, groupId: conversation.groupId))
                        .padding(.bottom, SidebarLayoutMetrics.listRowGap)
                }

                if conversations.count > maxCollapsed {
                    HStack {
                        VButton(
                            label: showAll ? "Show less" : "Show more",
                            style: .ghost,
                            size: .compact,
                            tintColor: VColor.contentTertiary
                        ) {
                            withAnimation(VAnimation.fast) { onToggleShowAll() }
                        }
                        Spacer()
                    }
                    .padding(.leading, VSpacing.xs + SidebarLayoutMetrics.iconSlotSize + VSpacing.xs - VSpacing.sm)
                    .padding(.bottom, VSpacing.xs)
                }
            }
            .padding(.bottom, VSpacing.xxs)
            .transition(.opacity)
        }
    }

    @ViewBuilder
    private var header: some View {
        HStack(spacing: VSpacing.xs) {
            VIconView(isHeaderHovered ? .chevronRight : .sparkles, size: isHeaderHovered ? SidebarLayoutMetrics.sectionChevronSize : 13)
                .foregroundStyle(VColor.contentTertiary)
                .rotationEffect(.degrees(isHeaderHovered && isExpanded ? 90 : 0))
                .animation(VAnimation.fast, value: isExpanded)
                .animation(VAnimation.fast, value: isHeaderHovered)
                .frame(width: SidebarLayoutMetrics.iconSlotSize, height: SidebarLayoutMetrics.iconSlotSize)

            Text("Reflections")
                .font(VFont.bodySmallDefault)
                .foregroundStyle(VColor.contentSecondary)

            Spacer()

            if !isExpanded && hasUnread {
                VBadge(style: .dot, color: VColor.systemMidStrong)
                    .transition(.opacity)
            }
        }
        .padding(.leading, VSpacing.xs)
        .padding(.trailing, SidebarLayoutMetrics.trailingIconPadding)
        .padding(.vertical, SidebarLayoutMetrics.rowVerticalPadding)
        .frame(minHeight: SidebarLayoutMetrics.rowMinHeight)
        .contentShape(Rectangle())
        .animation(VAnimation.fast, value: isHeaderHovered)
        .onTapGesture { withAnimation(VAnimation.fast) { onToggleExpand() } }
        .overlay(alignment: .trailing) {
            if conversations.count > 0 {
                Text("\(conversations.count)")
                    .font(VFont.labelSmall)
                    .foregroundStyle(VColor.contentTertiary)
                    .padding(.horizontal, VSpacing.sm - VSpacing.xxs)
                    .padding(.vertical, VSpacing.xxs)
                    .background(
                        Capsule()
                            .fill(VColor.contentTertiary.opacity(0.12))
                    )
                    .padding(.trailing, VSpacing.xs)
            }
        }
        .pointerCursor(onHover: { hovering in
            isHeaderHovered = hovering
        })
        .accessibilityElement(children: .combine)
        .accessibilityLabel(Text("Reflections"))
        .accessibilityHint(Text(isExpanded ? "Collapse reflections section" : "Expand reflections section"))
        .accessibilityAddTraits(.isHeader)
        .accessibilityAddTraits(.isButton)
        .accessibilityAction(.default) {
            withAnimation(VAnimation.fast) { onToggleExpand() }
        }
    }
}
