/**
 * Gemini embedding worker script, written to a temp .mjs file and run by a
 * separate bun process. Communicates via JSON-lines over stdin/stdout.
 *
 * Unlike the local ONNX worker, there is no model loading step - the worker
 * signals ready immediately and handles each request concurrently via fetch,
 * so the main event loop is never blocked by Gemini HTTP round-trips.
 *
 * Request shape:  { id, parts, taskType?, outputDimensionality? }
 * Cancel shape:   { cancel: id }
 * Response shape: { id, values } | { id, error }
 * Startup signal: { type: "ready" }
 */
export const GEMINI_WORKER_SCRIPT = `\
// gemini-embed-worker.mjs - auto-generated by embedding-gemini.ts
// Runs in a separate bun process, communicates via JSON-lines over stdin/stdout.
process.title = 'gemini-embed-worker';

const apiKey = process.env.GEMINI_EMBED_API_KEY || '';
const model = process.env.GEMINI_EMBED_MODEL || '';
const managedBaseUrl = process.env.GEMINI_EMBED_MANAGED_URL || '';

// No model loading needed - signal ready immediately.
process.stdout.write(JSON.stringify({ type: 'ready' }) + '\\n');

const decoder = new TextDecoder();
let buffer = '';

// Map of request id to AbortController so the parent can cancel in-flight fetches.
const controllers = new Map();

process.stdin.on('data', (chunk) => {
  buffer += typeof chunk === 'string' ? chunk : decoder.decode(chunk, { stream: true });
  let idx;
  while ((idx = buffer.indexOf('\\n')) !== -1) {
    const line = buffer.slice(0, idx);
    buffer = buffer.slice(idx + 1);
    if (!line.trim()) continue;
    let msg;
    try { msg = JSON.parse(line); } catch { continue; }
    if (msg.cancel !== undefined) {
      // Cancel an in-flight fetch by its request id.
      const ctrl = controllers.get(msg.cancel);
      if (ctrl) ctrl.abort();
    } else {
      // Each request is handled concurrently - fetch calls are independent.
      handleRequest(msg);
    }
  }
});

async function handleRequest(req) {
  const { id, parts, taskType, outputDimensionality } = req;
  const ctrl = new AbortController();
  controllers.set(id, ctrl);
  try {
    const body = { content: { parts } };
    if (taskType) body.taskType = taskType;
    if (outputDimensionality) body.outputDimensionality = outputDimensionality;

    const url = managedBaseUrl
      ? managedBaseUrl + '/v1beta/models/' + encodeURIComponent(model) + ':embedContent'
      : 'https://generativelanguage.googleapis.com/v1beta/models/' + encodeURIComponent(model) + ':embedContent?key=' + encodeURIComponent(apiKey);

    const headers = { 'Content-Type': 'application/json' };
    if (managedBaseUrl) headers['Authorization'] = 'Bearer ' + apiKey;

    const response = await fetch(url, { method: 'POST', headers, body: JSON.stringify(body), signal: ctrl.signal });
    if (!response.ok) {
      const text = await response.text();
      process.stdout.write(JSON.stringify({ id, error: 'Gemini embeddings request failed (' + response.status + '): ' + text }) + '\\n');
      return;
    }
    const payload = await response.json();
    const values = payload.embedding?.values;
    if (!Array.isArray(values) || values.length === 0) {
      process.stdout.write(JSON.stringify({ id, error: 'Gemini embeddings response missing vector values' }) + '\\n');
      return;
    }
    process.stdout.write(JSON.stringify({ id, values }) + '\\n');
  } catch (err) {
    // AbortError from cancellation is expected - no response needed.
    if (err.name !== 'AbortError') {
      process.stdout.write(JSON.stringify({ id, error: err.message || String(err) }) + '\\n');
    }
  } finally {
    controllers.delete(id);
  }
}

process.stdin.on('end', () => process.exit(0));
`;
