/**
 * Kaldi-compatible log-mel filterbank front end.
 *
 * The ECAPA-TDNN speaker model consumes fbank features, not raw audio, and
 * it was trained on features produced by Kaldi's `compute-fbank-feats` (via
 * `torchaudio.compliance.kaldi.fbank`). Feeding it anything else silently
 * degrades embeddings rather than failing, so this reproduces that exact
 * pipeline: framing, DC removal, preemphasis, window, power spectrum, mel
 * binning, log.
 *
 * `__tests__/fbank-parity.test.ts` checks the output against golden vectors
 * generated by the Python reference. Treat that test as the spec.
 */

/** Kaldi's mel scale. */
function melScale(freqHz: number): number {
  return 1127.0 * Math.log(1.0 + freqHz / 700.0);
}

export interface FbankOptions {
  sampleRate: number;
  /** Frame length in milliseconds. */
  frameLengthMs: number;
  /** Frame hop in milliseconds. */
  frameShiftMs: number;
  numMelBins: number;
  lowFreqHz: number;
  /** Upper edge; values <= 0 are taken as an offset from Nyquist. */
  highFreqHz: number;
  preemphasisCoefficient: number;
  removeDcOffset: boolean;
}

/**
 * Exactly the arguments WeSpeaker's `Speaker.compute_features` passes, with
 * Kaldi's defaults for everything it leaves alone. Changing any of these
 * invalidates every stored voiceprint, so they are not configurable per call.
 */
export const WESPEAKER_FBANK: FbankOptions = {
  sampleRate: 16000,
  frameLengthMs: 25,
  frameShiftMs: 10,
  numMelBins: 80,
  lowFreqHz: 20,
  highFreqHz: 0,
  preemphasisCoefficient: 0.97,
  removeDcOffset: true,
};

/** float32 machine epsilon, the floor Kaldi clamps mel energies to. */
const FLOAT32_EPSILON = 1.1920928955078125e-7;

export interface FbankResult {
  /** Row-major, `frames` rows of `dim` values. */
  data: Float32Array;
  frames: number;
  dim: number;
}

// ---------------------------------------------------------------
// FFT
// ---------------------------------------------------------------

/**
 * In-place iterative radix-2 complex FFT. `size` must be a power of two.
 *
 * A real-input FFT would be roughly twice as fast, but a 512-point complex
 * transform per 10 ms frame is already far below the cost of the model
 * itself, and this is much easier to verify.
 */
function fftInPlace(re: Float64Array, im: Float64Array, size: number): void {
  // Bit-reversal permutation.
  for (let i = 1, j = 0; i < size; i++) {
    let bit = size >> 1;
    for (; j & bit; bit >>= 1) {
      j ^= bit;
    }
    j ^= bit;
    if (i < j) {
      const tr = re[i]!;
      re[i] = re[j]!;
      re[j] = tr;
      const ti = im[i]!;
      im[i] = im[j]!;
      im[j] = ti;
    }
  }

  for (let len = 2; len <= size; len <<= 1) {
    const ang = (-2 * Math.PI) / len;
    const wRe = Math.cos(ang);
    const wIm = Math.sin(ang);
    for (let i = 0; i < size; i += len) {
      let curRe = 1;
      let curIm = 0;
      const half = len >> 1;
      for (let k = 0; k < half; k++) {
        const uRe = re[i + k]!;
        const uIm = im[i + k]!;
        const vRe = re[i + k + half]! * curRe - im[i + k + half]! * curIm;
        const vIm = re[i + k + half]! * curIm + im[i + k + half]! * curRe;
        re[i + k] = uRe + vRe;
        im[i + k] = uIm + vIm;
        re[i + k + half] = uRe - vRe;
        im[i + k + half] = uIm - vIm;
        const nextRe = curRe * wRe - curIm * wIm;
        curIm = curRe * wIm + curIm * wRe;
        curRe = nextRe;
      }
    }
  }
}

function nextPowerOfTwo(n: number): number {
  let p = 1;
  while (p < n) {
    p <<= 1;
  }
  return p;
}

// ---------------------------------------------------------------
// Windows and mel banks
// ---------------------------------------------------------------

/** Symmetric (`periodic=false`) Hamming window, Kaldi's coefficients. */
function hammingWindow(size: number): Float64Array {
  const w = new Float64Array(size);
  for (let i = 0; i < size; i++) {
    w[i] = 0.54 - 0.46 * Math.cos((2 * Math.PI * i) / (size - 1));
  }
  return w;
}

/**
 * Triangular mel filterbank over FFT bins, laid out row-major as
 * `numMelBins x (paddedWindowSize / 2 + 1)`.
 *
 * Kaldi builds the bank over `paddedWindowSize / 2` bins and leaves the
 * Nyquist bin at zero, so the final column is always zero. Keeping it makes
 * the matrix line up with the power spectrum length.
 */
function melFilterbank(
  numMelBins: number,
  paddedWindowSize: number,
  sampleRate: number,
  lowFreqHz: number,
  highFreqHz: number,
): Float64Array {
  const numFftBins = paddedWindowSize / 2;
  const nyquist = 0.5 * sampleRate;
  const highFreq = highFreqHz <= 0 ? nyquist + highFreqHz : highFreqHz;
  const fftBinWidth = sampleRate / paddedWindowSize;

  const melLow = melScale(lowFreqHz);
  const melHigh = melScale(highFreq);
  // Divided by numMelBins + 1 because the triangles overlap at the edges.
  const melDelta = (melHigh - melLow) / (numMelBins + 1);

  const cols = numFftBins + 1;
  const bank = new Float64Array(numMelBins * cols);

  for (let bin = 0; bin < numMelBins; bin++) {
    const leftMel = melLow + bin * melDelta;
    const centerMel = melLow + (bin + 1) * melDelta;
    const rightMel = melLow + (bin + 2) * melDelta;
    const row = bin * cols;
    for (let k = 0; k < numFftBins; k++) {
      const mel = melScale(fftBinWidth * k);
      const upSlope = (mel - leftMel) / (centerMel - leftMel);
      const downSlope = (rightMel - mel) / (rightMel - centerMel);
      const value = Math.min(upSlope, downSlope);
      bank[row + k] = value > 0 ? value : 0;
    }
  }
  return bank;
}

// The bank depends only on constants, so build it once per configuration.
const bankCache = new Map<string, Float64Array>();
function cachedMelFilterbank(
  numMelBins: number,
  paddedWindowSize: number,
  sampleRate: number,
  lowFreqHz: number,
  highFreqHz: number,
): Float64Array {
  const key = `${numMelBins}:${paddedWindowSize}:${sampleRate}:${lowFreqHz}:${highFreqHz}`;
  let bank = bankCache.get(key);
  if (!bank) {
    bank = melFilterbank(
      numMelBins,
      paddedWindowSize,
      sampleRate,
      lowFreqHz,
      highFreqHz,
    );
    bankCache.set(key, bank);
  }
  return bank;
}

// ---------------------------------------------------------------
// Public API
// ---------------------------------------------------------------

/**
 * Number of frames Kaldi produces for a signal of `numSamples`, using
 * `snip_edges=true`: frames that would run off the end are dropped rather
 * than padded, so short signals can yield zero frames.
 */
export function frameCount(
  numSamples: number,
  options: FbankOptions = WESPEAKER_FBANK,
): number {
  const windowSize = Math.round(
    options.sampleRate * options.frameLengthMs * 0.001,
  );
  const windowShift = Math.round(
    options.sampleRate * options.frameShiftMs * 0.001,
  );
  if (numSamples < windowSize) {
    return 0;
  }
  return 1 + Math.floor((numSamples - windowSize) / windowShift);
}

/**
 * Compute log-mel filterbank features from mono PCM.
 *
 * `samples` must be normalized to roughly [-1, 1] (what WAV decoding to
 * float gives you), NOT int16-scale. WeSpeaker asks torchaudio for
 * unnormalized audio but torchaudio 2.x ignores that flag, so the model was
 * effectively fed normalized input, and matching it matters.
 */
export function computeFbank(
  samples: Float32Array,
  options: FbankOptions = WESPEAKER_FBANK,
): FbankResult {
  const { sampleRate, numMelBins, preemphasisCoefficient, removeDcOffset } =
    options;
  const windowSize = Math.round(sampleRate * options.frameLengthMs * 0.001);
  const windowShift = Math.round(sampleRate * options.frameShiftMs * 0.001);
  const paddedWindowSize = nextPowerOfTwo(windowSize);
  const frames = frameCount(samples.length, options);

  const out = new Float32Array(frames * numMelBins);
  if (frames === 0) {
    return { data: out, frames: 0, dim: numMelBins };
  }

  const window = hammingWindow(windowSize);
  const spectrumBins = paddedWindowSize / 2 + 1;
  const bank = cachedMelFilterbank(
    numMelBins,
    paddedWindowSize,
    sampleRate,
    options.lowFreqHz,
    options.highFreqHz,
  );

  const frame = new Float64Array(windowSize);
  const re = new Float64Array(paddedWindowSize);
  const im = new Float64Array(paddedWindowSize);
  const power = new Float64Array(spectrumBins);

  for (let f = 0; f < frames; f++) {
    const offset = f * windowShift;

    for (let i = 0; i < windowSize; i++) {
      frame[i] = samples[offset + i]!;
    }

    if (removeDcOffset) {
      let sum = 0;
      for (let i = 0; i < windowSize; i++) {
        sum += frame[i]!;
      }
      const mean = sum / windowSize;
      for (let i = 0; i < windowSize; i++) {
        frame[i]! -= mean;
      }
    }

    // Preemphasis reads the pre-filter neighbour, so walk backwards to avoid
    // feeding an already-filtered sample into the next step. Kaldi replicates
    // the first sample rather than reaching outside the frame.
    if (preemphasisCoefficient !== 0) {
      for (let i = windowSize - 1; i > 0; i--) {
        frame[i]! -= preemphasisCoefficient * frame[i - 1]!;
      }
      frame[0]! -= preemphasisCoefficient * frame[0]!;
    }

    re.fill(0);
    im.fill(0);
    for (let i = 0; i < windowSize; i++) {
      re[i] = frame[i]! * window[i]!;
    }

    fftInPlace(re, im, paddedWindowSize);

    for (let k = 0; k < spectrumBins; k++) {
      power[k] = re[k]! * re[k]! + im[k]! * im[k]!;
    }

    const rowOut = f * numMelBins;
    for (let bin = 0; bin < numMelBins; bin++) {
      const rowBank = bin * spectrumBins;
      let energy = 0;
      for (let k = 0; k < spectrumBins; k++) {
        energy += bank[rowBank + k]! * power[k]!;
      }
      out[rowOut + bin] = Math.log(
        energy > FLOAT32_EPSILON ? energy : FLOAT32_EPSILON,
      );
    }
  }

  return { data: out, frames, dim: numMelBins };
}

/**
 * Per-utterance cepstral mean normalization: subtract each coefficient's
 * mean over time. WeSpeaker applies this before the model, and it is what
 * makes the features insensitive to a constant gain difference between clips.
 */
export function applyCmn(result: FbankResult): FbankResult {
  const { data, frames, dim } = result;
  if (frames === 0) {
    return result;
  }
  const means = new Float64Array(dim);
  for (let f = 0; f < frames; f++) {
    const row = f * dim;
    for (let d = 0; d < dim; d++) {
      means[d]! += data[row + d]!;
    }
  }
  for (let d = 0; d < dim; d++) {
    means[d]! /= frames;
  }
  for (let f = 0; f < frames; f++) {
    const row = f * dim;
    for (let d = 0; d < dim; d++) {
      data[row + d] = data[row + d]! - means[d]!;
    }
  }
  return result;
}
