/**
 * Runs the speaker-embedding forward pass in a separate bun process.
 *
 * ONNX Runtime cannot be bundled into the daemon: `bun --compile` embeds the
 * `.node` addon but not the 44 MB `libonnxruntime` dylib it links against, so
 * the addon fails to `dlopen` at startup, and a compiled binary cannot resolve
 * bare specifiers from `/$bunfs/root` either. The daemon therefore reuses the
 * ONNX Runtime that `EmbeddingRuntimeManager` already downloads post-hatch on
 * every start, and runs inference in a standalone bun process where
 * `node_modules` resolution works normally.
 *
 * The fbank front end deliberately stays in the host process: it is pure
 * TypeScript and `fbank-parity.test.ts` guards it against silent numeric
 * drift, so only the forward pass crosses the process boundary.
 *
 * One spawn serves one request. Cold spawn measures ~40-90 ms end to end
 * (import ~10 ms, session create ~20-45 ms, inference ~8 ms), which is well
 * inside the budget for user-initiated enroll and identify. Callers batch all
 * clips of a request into a single spawn.
 */

import { existsSync } from "node:fs";
import { renameSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { EmbeddingRuntimeManager } from "../persistence/embeddings/embedding-runtime-manager.js";
import { getLogger } from "../util/logger.js";
import { getEmbeddingModelsDir } from "../util/platform.js";
import { workerComputeEnv } from "../util/worker-compute.js";
import { workerMemoryEnv } from "../util/worker-memory.js";
import type { FbankResult } from "./fbank.js";

const log = getLogger("voiceprint-worker");

const WORKER_FILENAME = "voiceprint-worker.mjs";

/** Raised when the ONNX runtime needed for speaker embedding is unavailable. */
export class VoiceprintRuntimeUnavailableError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "VoiceprintRuntimeUnavailableError";
  }
}

/**
 * The worker script, emitted next to the downloaded runtime.
 *
 * Written as a generated string rather than a checked-in `.ts` file because
 * the daemon bundle inlines its own module graph; a sibling source file would
 * not exist on disk at runtime. Living beside the runtime's `node_modules`
 * is what lets the bare `onnxruntime-node` import resolve.
 */
export function generateVoiceprintWorkerScript(): string {
  return `\
// voiceprint-worker.mjs — Auto-generated by src/voiceprint/voiceprint-worker.ts
// Reads one JSON request on stdin, writes one JSON response on stdout, exits.
process.title = 'voiceprint-worker';
import * as ort from 'onnxruntime-node';

const modelPath = process.argv[2];

// Cap the ONNX intra-op thread pool. Left unset, ONNX takes one thread per
// physical core and starves foreground work; the host computes the cap in
// util/worker-compute.ts and passes it in the environment.
const intraOpNumThreads = Number(process.env.VELLUM_ONNX_INTRA_OP_THREADS);
const sessionOptions =
  Number.isInteger(intraOpNumThreads) && intraOpNumThreads > 0
    ? { intraOpNumThreads }
    : undefined;

function readStdin() {
  return new Promise((resolve, reject) => {
    const chunks = [];
    process.stdin.on('data', (c) => chunks.push(typeof c === 'string' ? Buffer.from(c) : c));
    process.stdin.on('end', () => resolve(Buffer.concat(chunks).toString('utf8')));
    process.stdin.on('error', reject);
  });
}

try {
  const request = JSON.parse(await readStdin());
  const session = await ort.InferenceSession.create(modelPath, sessionOptions);
  const inputName = session.inputNames[0];
  const outputName = session.outputNames[0];

  const embeddings = [];
  for (const clip of request.clips) {
    const bytes = Buffer.from(clip.b64, 'base64');
    // Copy into a fresh buffer: the Buffer may be a view onto a larger pool
    // whose byteOffset is not float-aligned.
    const feats = new Float32Array(clip.frames * clip.dim);
    Buffer.from(feats.buffer).set(bytes);
    const tensor = new ort.Tensor('float32', feats, [1, clip.frames, clip.dim]);
    const outputs = await session.run({ [inputName]: tensor });
    embeddings.push(Array.from(outputs[outputName].data));
  }

  process.stdout.write(JSON.stringify({ embeddings }) + '\\n');
} catch (err) {
  process.stdout.write(
    JSON.stringify({ error: err && err.message ? err.message : String(err) }) + '\\n',
  );
  process.exit(1);
}
`;
}

/**
 * Write the worker script beside the downloaded runtime.
 *
 * Rewritten on every call so an edit here reaches existing installs, and
 * because `EmbeddingRuntimeManager` deletes non-dotfile entries from this
 * directory when it upgrades the runtime — this self-heals that.
 */
function ensureWorkerScript(baseDir: string): string {
  const workerPath = join(baseDir, WORKER_FILENAME);
  // Write-then-rename so a concurrent spawn never reads a partial script.
  const tmp = `${workerPath}.${process.pid}.tmp`;
  writeFileSync(tmp, generateVoiceprintWorkerScript());
  renameSync(tmp, workerPath);
  return workerPath;
}

/**
 * Run the embedding model over one or more fbank feature matrices.
 *
 * Returns raw (un-normalized) embeddings in the same order as `features`.
 */
export async function runEmbeddingWorker(
  features: FbankResult[],
  modelPath: string,
): Promise<Float32Array[]> {
  if (features.length === 0) {
    return [];
  }

  const runtimeManager = new EmbeddingRuntimeManager();
  if (!runtimeManager.isReady()) {
    log.info("ONNX runtime not yet available, waiting for download...");
    await runtimeManager.ensureInstalled();
  }

  const bunPath = runtimeManager.getBunPath();
  if (!bunPath) {
    throw new VoiceprintRuntimeUnavailableError(
      "Speaker embedding unavailable: no bun binary found",
    );
  }

  const baseDir = getEmbeddingModelsDir();
  if (!existsSync(join(baseDir, "node_modules", "onnxruntime-node"))) {
    throw new VoiceprintRuntimeUnavailableError(
      "Speaker embedding unavailable: ONNX runtime is not installed",
    );
  }
  const workerPath = ensureWorkerScript(baseDir);

  const request = {
    clips: features.map((f) => ({
      b64: Buffer.from(
        f.data.buffer,
        f.data.byteOffset,
        f.data.byteLength,
      ).toString("base64"),
      frames: f.frames,
      dim: f.dim,
    })),
  };

  const proc = Bun.spawn({
    cmd: [bunPath, "--smol", workerPath, modelPath],
    windowsHide: true,
    env: { ...workerMemoryEnv(), ...workerComputeEnv() },
    stdin: "pipe",
    stdout: "pipe",
    stderr: "pipe",
    cwd: baseDir,
  });

  proc.stdin.write(JSON.stringify(request));
  await proc.stdin.end();

  const [stdout, stderr] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
  ]);
  await proc.exited;

  let parsed: { embeddings?: number[][]; error?: string };
  try {
    parsed = JSON.parse(stdout.trim());
  } catch {
    throw new Error(
      `Speaker embedding worker produced no usable output (exit ${proc.exitCode})${
        stderr.trim() ? `: ${stderr.trim()}` : ""
      }`,
    );
  }

  if (parsed.error) {
    throw new Error(`Speaker embedding worker failed: ${parsed.error}`);
  }
  if (!parsed.embeddings || parsed.embeddings.length !== features.length) {
    throw new Error(
      `Expected ${features.length} embeddings, got ${parsed.embeddings?.length ?? 0}`,
    );
  }

  return parsed.embeddings.map((e) => Float32Array.from(e));
}
