import { AlertCircle, Check, Loader2 } from "lucide-react";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";

import { Button } from "@vellum/design-library/components/button";
import { Input } from "@vellum/design-library/components/input";
import { toast } from "@vellum/design-library/components/toast";
import { SettingsCard } from "@/domains/settings/components/settings-card.js";
import { useAuthStore } from "@/stores/auth-store.js";
import { looksAutoGenerated } from "@/lib/account/handle-heuristics.js";
import {
  checkUsernameAvailable,
  fetchMe,
  type UsernameAvailability,
  type UsernameErrorCode,
  updateMe,
  USERNAME_ERROR_COPY,
  type UserMe,
} from "@/lib/account/profile.js";

const AVAILABILITY_DEBOUNCE_MS = 300;
const SAVED_HOLD_MS = 1400;

type SaveStatus = "idle" | "saving" | "saved" | "error";

interface CardBodyProps {
  initial: UserMe;
  onSaved: (next: UserMe) => void;
}

function ProfileCardBody({ initial, onSaved }: CardBodyProps) {
  const [value, setValue] = useState(initial.username);
  const [availability, setAvailability] = useState<UsernameAvailability | null>(
    null,
  );
  const [isChecking, setIsChecking] = useState(false);
  const [saveStatus, setSaveStatus] = useState<SaveStatus>("idle");
  const [serverError, setServerError] = useState<string | null>(null);
  const refreshSession = useAuthStore.use.refreshSession();
  const prefersReducedMotion = useReducedMotion();

  const inflightRef = useRef<AbortController | null>(null);

  const normalized = useMemo(() => value.trim().toLowerCase(), [value]);
  const isUnchanged = normalized === initial.username.toLowerCase();

  useEffect(() => {
    if (isUnchanged || normalized.length === 0) {
      setIsChecking(false);
      inflightRef.current?.abort();
      return;
    }

    const controller = new AbortController();
    inflightRef.current?.abort();
    inflightRef.current = controller;
    setIsChecking(true);

    const timer = window.setTimeout(async () => {
      try {
        const result = await checkUsernameAvailable(
          normalized,
          controller.signal,
        );
        if (!controller.signal.aborted) {
          setAvailability(result);
        }
      } catch (err) {
        if (!controller.signal.aborted) {
          setServerError(
            err instanceof Error
              ? err.message
              : "Couldn't check availability.",
          );
        }
      } finally {
        if (!controller.signal.aborted) {
          setIsChecking(false);
        }
      }
    }, AVAILABILITY_DEBOUNCE_MS);

    return () => {
      window.clearTimeout(timer);
      controller.abort();
    };
  }, [normalized, isUnchanged]);

  const errorText: string | null = (() => {
    if (serverError) return serverError;
    if (availability && !availability.available) {
      const code = availability.code as UsernameErrorCode | null;
      return (
        availability.message ??
        (code ? USERNAME_ERROR_COPY[code] : "Please choose a different handle.")
      );
    }
    return null;
  })();

  const helperText: string | null = (() => {
    if (errorText) return null;
    if (isUnchanged) {
      if (looksAutoGenerated(initial.username)) {
        return "Your handle was auto-generated at signup — pick one you like.";
      }
      return null;
    }
    if (isChecking) return "Checking availability…";
    if (availability?.available) return "Available.";
    return null;
  })();

  const isSaveable =
    !isUnchanged &&
    !isChecking &&
    availability?.available !== false &&
    saveStatus !== "saving";

  const handleSave = useCallback(async () => {
    if (!isSaveable) return;
    setSaveStatus("saving");
    setServerError(null);

    const result = await updateMe({ username: normalized });
    if (result.kind === "ok") {
      setSaveStatus("saved");
      onSaved(result.data);
      void refreshSession();
      toast.success("Profile updated.");
      window.setTimeout(() => setSaveStatus("idle"), SAVED_HOLD_MS);
      return;
    }
    if (result.kind === "taken") {
      setSaveStatus("idle");
      setAvailability({
        available: false,
        code: "taken",
        message: result.message,
      });
      return;
    }
    if (result.kind === "invalid") {
      setSaveStatus("idle");
      setAvailability({
        available: false,
        code: (result.code ?? null) as UsernameErrorCode | null,
        message: result.message,
      });
      return;
    }
    setSaveStatus("error");
    setServerError(result.message);
    toast.error(result.message);
  }, [isSaveable, normalized, onSaved, refreshSession]);

  const rightIcon = (() => {
    if (isUnchanged && value.length > 0) return null;
    if (value.length === 0) return null;
    const motionKey = isChecking
      ? "checking"
      : availability?.available
        ? "available"
        : availability?.available === false
          ? "invalid"
          : null;
    if (!motionKey) return null;
    return (
      <AnimatePresence mode="wait" initial={false}>
        <motion.span
          key={motionKey}
          initial={prefersReducedMotion ? false : { opacity: 0, scale: 0.85 }}
          animate={{ opacity: 1, scale: 1 }}
          exit={prefersReducedMotion ? undefined : { opacity: 0, scale: 0.85 }}
          transition={{ duration: 0.14, ease: "easeOut" }}
          className="flex items-center"
          aria-hidden={motionKey !== "available" && motionKey !== "invalid"}
        >
          {motionKey === "checking" && (
            <Loader2 className="h-4 w-4 animate-spin text-[var(--content-tertiary)]" />
          )}
          {motionKey === "available" && (
            <Check
              className="h-4 w-4 text-[var(--system-positive-strong)]"
              aria-label="Available"
            />
          )}
          {motionKey === "invalid" && (
            <AlertCircle
              className="h-4 w-4 text-[var(--system-negative-strong)]"
              aria-label="Not available"
            />
          )}
        </motion.span>
      </AnimatePresence>
    );
  })();

  const previewHandle = normalized.length > 0 ? normalized : initial.username;
  const previewIsDirty = !isUnchanged && normalized.length > 0;

  const saveLabel = (() => {
    switch (saveStatus) {
      case "saving":
        return (
          <span className="inline-flex items-center gap-1.5">
            <Loader2 className="h-3.5 w-3.5 animate-spin" aria-hidden />
            Saving…
          </span>
        );
      case "saved":
        return (
          <span className="inline-flex items-center gap-1.5">
            <Check className="h-3.5 w-3.5" aria-hidden />
            Saved
          </span>
        );
      default:
        return "Save";
    }
  })();

  return (
    <div className="flex flex-col gap-4">
      <Input
        label="Handle"
        value={value}
        onChange={(e) => {
          setValue(e.target.value.replace(/\s+/g, ""));
          setAvailability(null);
          setServerError(null);
        }}
        autoCorrect="off"
        autoCapitalize="none"
        spellCheck={false}
        maxLength={30}
        leftIcon={
          <span
            className="select-none font-mono text-[var(--content-tertiary)]"
            aria-hidden
          >
            @
          </span>
        }
        rightIcon={rightIcon}
        errorText={errorText ?? undefined}
        helperText={
          helperText ??
          "Lowercase letters, digits, hyphens, and underscores. 3–30 characters."
        }
        aria-invalid={Boolean(errorText)}
        fullWidth
      />

      <div
        className="flex items-baseline gap-2 text-label-small-default text-[var(--content-tertiary)]"
        aria-live="polite"
      >
        <span>Appears as</span>
        <AnimatePresence mode="popLayout" initial={false}>
          <motion.span
            key={previewHandle}
            initial={prefersReducedMotion ? false : { opacity: 0, y: 1 }}
            animate={{ opacity: 1, y: 0 }}
            exit={prefersReducedMotion ? undefined : { opacity: 0, y: -1 }}
            transition={{ duration: 0.14, ease: "easeOut" }}
            className={
              "font-mono " +
              (previewIsDirty
                ? "text-[var(--content-primary)]"
                : "text-[var(--content-secondary)]")
            }
          >
            @{previewHandle}
          </motion.span>
        </AnimatePresence>
      </div>

      <div className="flex justify-end">
        <Button
          variant="primary"
          size="compact"
          onClick={handleSave}
          disabled={!isSaveable}
          aria-live="polite"
        >
          {saveLabel}
        </Button>
      </div>
    </div>
  );
}

function ProfileCardSkeleton() {
  return (
    <div className="flex flex-col gap-4" aria-busy aria-live="polite">
      <div className="flex flex-col gap-2">
        <div className="h-3 w-16 animate-pulse rounded bg-[var(--surface-muted)]" />
        <div className="h-9 w-full animate-pulse rounded-md bg-[var(--surface-muted)]" />
        <div className="h-3 w-72 animate-pulse rounded bg-[var(--surface-muted)]" />
      </div>
      <div className="h-9 w-full animate-pulse rounded-md bg-[var(--surface-muted)]" />
      <div className="flex items-center justify-between gap-3">
        <div className="h-3 w-60 animate-pulse rounded bg-[var(--surface-muted)]" />
        <div className="h-7 w-16 animate-pulse rounded-md bg-[var(--surface-muted)]" />
      </div>
      <span className="sr-only">Loading your profile…</span>
    </div>
  );
}

export function ProfileCard() {
  const [me, setMe] = useState<UserMe | null>(null);
  const [error, setError] = useState<string | null>(null);
  const prefersReducedMotion = useReducedMotion();

  useEffect(() => {
    let cancelled = false;
    void fetchMe()
      .then((data) => {
        if (!cancelled) setMe(data);
      })
      .catch((err) => {
        if (!cancelled) {
          setError(
            err instanceof Error ? err.message : "Failed to load profile.",
          );
        }
      });
    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <SettingsCard title="Profile" subtitle="Your public handle on Vellum.">
      {error ? (
        <p className="text-body-small-default text-[var(--system-negative-strong)]">
          {error}
        </p>
      ) : me ? (
        <motion.div
          initial={prefersReducedMotion ? false : { opacity: 0, y: 4 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.22, ease: "easeOut" }}
        >
          <ProfileCardBody initial={me} onSaved={setMe} />
        </motion.div>
      ) : (
        <ProfileCardSkeleton />
      )}
    </SettingsCard>
  );
}
