import { FullNavBar } from "@/components/marketing/CommunityPage/_FullNavBar";
import { WorkflowCTA } from "@/components/marketing/VellumHomepage/WorkflowCTA";

export function PrivacyPolicyBody() {
  return (
    <>
      <FullNavBar />
      <main className="main-wrapper">
        <div className="section_docs">
          <div className="padding-global">
            <div className="container-new docs">
              <div className="padding-section-medium">
                <div className="docs-content">
                  <h1 className="heading-1-new text-color-white font-playfair">
                    Privacy Policy
                  </h1>
                  <p className="u-text-regular text-color-light-gray">
                    This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                  </p>
                  <p className="u-text-small text-color-gray">
                    <strong>Last updated: October 21, 2025</strong>
                  </p>

                  <h2 className="heading-2-new text-color-white">Interpretation and Definitions</h2>
                  
                  <h3 className="heading-3-new text-color-white">Interpretation</h3>
                  <p className="u-text-regular text-color-light-gray">
                    The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                  </p>

                  <h3 className="heading-3-new text-color-white">Definitions</h3>
                  <p className="u-text-regular text-color-light-gray">For the purposes of this Privacy Policy:</p>
                  <ul className="docs-list">
                    <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                    <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                    <li><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Vocify Inc., 169 Madison Avenue Unit 2323 New York NY 10016.</li>
                    <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                    <li><strong>Country</strong> refers to: United States</li>
                    <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                    <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                    <li><strong>Service</strong> refers to the Website.</li>
                    <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
                    <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                    <li><strong>Website</strong> refers to Vellum, accessible from <a href="https://www.vellum.ai/" target="_blank" rel="noreferrer">https://www.vellum.ai/</a></li>
                    <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                  </ul>

                  <h2 className="heading-2-new text-color-white">Collecting and Using Your Personal Data</h2>
                  
                  <h3 className="heading-3-new text-color-white">Types of Data Collected</h3>
                  
                  <h4 className="heading-4-new text-color-white">Personal Data</h4>
                  <p className="u-text-regular text-color-light-gray">
                    While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
                  </p>
                  <ul className="docs-list">
                    <li>Email address</li>
                    <li>Usage Data</li>
                  </ul>

                  <h4 className="heading-4-new text-color-white">Usage Data</h4>
                  <p className="u-text-regular text-color-light-gray">
                    Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                  </p>
                  <p className="u-text-regular text-color-light-gray">
                    When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
                  </p>
                  <p className="u-text-regular text-color-light-gray">
                    We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
                  </p>
                  <p className="u-text-regular text-color-light-gray">
                    While using Vellum, You may authenticate with integrations to use their tools in Vellum. Note that Google user data can&apos;t be used with xAI or DeepSeek models.
                  </p>

                  <h3 className="heading-3-new text-color-white">Tracking Technologies and Cookies</h3>
                  <p className="u-text-regular text-color-light-gray">
                    We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
                  </p>
                  <ul className="docs-list">
                    <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</li>
                    <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics.</li>
                  </ul>
                  <p className="u-text-regular text-color-light-gray">
                    Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.
                  </p>
                  <p className="u-text-regular text-color-light-gray">
                    We use both Session and Persistent Cookies for the purposes set out below:
                  </p>
                  <ul className="docs-list">
                    <li>
                      <strong>Necessary / Essential Cookies</strong>
                      <br />Type: Session Cookies
                      <br />Administered by: Us
                      <br />Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.
                    </li>
                    <li>
                      <strong>Cookies Policy / Notice Acceptance Cookies</strong>
                      <br />Type: Persistent Cookies
                      <br />Administered by: Us
                      <br />Purpose: These Cookies identify if users have accepted the use of cookies on the Website.
                    </li>
                    <li>
                      <strong>Functionality Cookies</strong>
                      <br />Type: Persistent Cookies
                      <br />Administered by: Us
                      <br />Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.
                    </li>
                  </ul>

                  <h3 className="heading-3-new text-color-white">Use of Your Personal Data</h3>
                  <p className="u-text-regular text-color-light-gray">
                    The Company may use Personal Data for the following purposes:
                  </p>
                  <ul className="docs-list">
                    <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
                    <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
                    <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
                    <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application&apos;s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
                    <li><strong>To communicate with You</strong> about updates, new features, or changes directly related to the Service You use, unless You have opted not to receive such communications.</li>
                    <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
                    <li><strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</li>
                    <li><strong>For other purposes:</strong> We may use Your information for purposes such as data analysis, identifying usage trends, and evaluating and improving our Service&apos;s functionality and user experience.</li>
                  </ul>
                  <p className="u-text-regular text-color-light-gray">
                    We only use personal data to operate, maintain, and improve the features and performance of our Service.
                  </p>
                  <p className="u-text-regular text-color-light-gray">
                    We may share Your personal information in the following situations:
                  </p>
                  <ul className="docs-list">
                    <li><strong>With Service Providers:</strong> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</li>
                    <li><strong>For business transfers:</strong> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
                    <li><strong>With Affiliates:</strong> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
                    <li><strong>With business partners:</strong> We may share Your information with Our business partners to offer You certain products, services or promotions.</li>
                    <li><strong>With other users:</strong> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
      <WorkflowCTA />
    </>
  );
}
