/**
 * Suggested prompt producer for the Home feed.
 *
 * Returns an array of `SuggestedPrompt` items shown at the top of the
 * Home page as conversation starters. All prompts are generated by the
 * assistant based on the user's connected services and context —
 * read from an in-memory cache in the GET path; generation runs in
 * the background via `refreshAssistantSuggestedPrompts`.
 */

import { resolveCallSiteConfig } from "../config/llm-resolver.js";
import { getConfig } from "../config/loader.js";
import { buildSystemPrompt } from "../prompts/system-prompt.js";
import { getConfiguredProvider } from "../providers/provider-send-message.js";
import { buildAssistantEvent } from "../runtime/assistant-event.js";
import { assistantEventHub } from "../runtime/assistant-event-hub.js";
import { runBtwSidechain } from "../runtime/btw-sidechain.js";
import { formatIntegrationSummary } from "../schedule/integration-status.js";
import { getLogger } from "../util/logger.js";
import type { SuggestedPrompt } from "./feed-types.js";

const log = getLogger("suggested-prompts");

const LLM_SUGGESTIONS_TIMEOUT_MS = 5_000;
const LLM_CACHE_TTL_MS = 30 * 60 * 1000; // 30 minutes

// ---------------------------------------------------------------------------
// In-memory cache for LLM-generated suggestions
// ---------------------------------------------------------------------------

let cachedLLMPrompts: SuggestedPrompt[] = [];
let cachedLLMPromptsAt = 0;

/**
 * Return cached assistant-generated prompts. No LLM calls happen in
 * this path — safe for GET. Returns an empty array until the first
 * background refresh populates the cache.
 */
export async function getSuggestedPrompts(): Promise<SuggestedPrompt[]> {
  if (Date.now() - cachedLLMPromptsAt < LLM_CACHE_TTL_MS) {
    return [...cachedLLMPrompts];
  }
  return [];
}

/**
 * Drops the in-memory suggestion cache so the next background refresh
 * regenerates prompts with current integration state.
 *
 * Called from OAuth connect/disconnect paths so suggestions reflect the
 * new state within one reload instead of waiting for the 30-minute TTL.
 */
export function invalidateAssistantSuggestedPromptsCache(): void {
  cachedLLMPrompts = [];
  cachedLLMPromptsAt = 0;
  assistantEventHub
    .publish(
      buildAssistantEvent({
        type: "home_feed_updated",
        updatedAt: new Date().toISOString(),
        newItemCount: 0,
      }),
    )
    .catch((err) => {
      log.warn(
        { err },
        "Failed to publish home_feed_updated after prompt cache invalidation",
      );
    });
}

/**
 * Generate LLM-based suggestion prompts and write them to the in-memory
 * cache. No-ops when the cache is still fresh. Intended for background
 * invocation (daemon startup / periodic refresh), not the GET path.
 */
export async function refreshAssistantSuggestedPrompts(): Promise<void> {
  if (Date.now() - cachedLLMPromptsAt < LLM_CACHE_TTL_MS) {
    return;
  }

  try {
    const llmPrompts = await generateAssistantPrompts();
    cachedLLMPrompts = llmPrompts;
    cachedLLMPromptsAt = Date.now();
  } catch (err) {
    log.warn({ err }, "Failed to refresh assistant suggested prompts");
  }
}

// ---------------------------------------------------------------------------
// LLM-generated suggestions
// ---------------------------------------------------------------------------

interface LLMSuggestion {
  label: string;
  prompt: string;
}

/**
 * Ask the LLM to generate contextual conversation-starter suggestions
 * based on the assistant's persona and the user's connected services.
 * Returns an empty array on failure.
 */
async function generateAssistantPrompts(): Promise<SuggestedPrompt[]> {
  const config = getConfig();
  const resolved = resolveCallSiteConfig("homeSuggestedPrompts", config.llm);

  const provider = await getConfiguredProvider("homeSuggestedPrompts");
  if (!provider) {
    return [];
  }

  const systemPrompt = buildSystemPrompt({
    excludeBootstrap: true,
    excludeCustomPrefix: true,
  });

  let integrationContext = "";
  try {
    integrationContext = `\nConnected integrations: ${await formatIntegrationSummary()}`;
  } catch {
    // Best-effort — continue without integration info
  }

  const result = await runBtwSidechain({
    content:
      "Suggest 2-3 short, actionable conversation starters for the home page. " +
      "Each should be something specific and helpful you can do for the user right now. " +
      "Focus on things the user's connected services enable — don't suggest connecting services they already have. " +
      "You may suggest connecting a service only if it's not yet connected and would be genuinely useful." +
      integrationContext +
      ' Return ONLY a JSON array of objects with "label" (max 5 words) and "prompt" (the full message to send). ' +
      "No markdown fences, no explanation.",
    provider,
    systemPrompt,
    messages: [],
    tools: [],
    callSite: "homeSuggestedPrompts",
    maxTokens: resolved.maxTokens,
    timeoutMs: LLM_SUGGESTIONS_TIMEOUT_MS,
  });

  const text = result.text.trim();
  if (!text) {
    return [];
  }

  const parsed = parseLLMSuggestions(text);
  return parsed.map((s, i) => ({
    id: `assistant-${i}-${s.label.toLowerCase().replace(/\s+/g, "-")}`,
    label: s.label,
    prompt: s.prompt,
    source: "assistant" as const,
  }));
}

function parseLLMSuggestions(text: string): LLMSuggestion[] {
  try {
    const cleaned = text
      .replace(/^```(?:json)?\n?/m, "")
      .replace(/\n?```$/m, "");
    const parsed = JSON.parse(cleaned);
    if (!Array.isArray(parsed)) {
      return [];
    }
    return parsed.filter(
      (item): item is LLMSuggestion =>
        typeof item === "object" &&
        item !== null &&
        typeof item.label === "string" &&
        typeof item.prompt === "string",
    );
  } catch {
    log.warn("Failed to parse LLM suggestions response");
    return [];
  }
}
