apiVersion: v1
kind: ServiceAccount
metadata:
  name: vellum-assistant
  namespace: ${NAMESPACE}
  annotations:
    iam.gke.io/gcp-service-account: vellum-previews-app@vellum-nonprod.iam.gserviceaccount.com
