/**
 * Postinstall adapter that massages the upstream `caveman` Claude Code plugin
 * into a plugin the Vellum loader can run.
 *
 * Why this exists: `caveman` (https://github.com/JuliusBrussee/caveman) ships a
 * Claude Code plugin layout — a `.claude-plugin/plugin.json` manifest whose
 * behavior lives in `SessionStart`/`UserPromptSubmit` hooks that shell out to
 * bundled `node` scripts, plus the ruleset prose in `skills/caveman/SKILL.md`.
 * Vellum's loader expects a different shape: a `package.json` whose `name`
 * matches the directory and that declares the `@vellumai/plugin-api` peer
 * dependency, with hooks as `hooks/<hook-name>.ts` modules (default export =
 * the hook function). Installed verbatim, caveman therefore loads as a
 * name-mismatched, peer-dep-less directory with no Vellum hooks, so it does
 * nothing.
 *
 * This adapter is curated, reviewed Vellum code (it lives in our repo, not the
 * upstream clone) and is invoked via npm's native `scripts.postinstall` after
 * the installer overlays it onto the freshly cloned tree. It never executes
 * caveman's own lifecycle scripts. It performs a deterministic, file-only
 * translation:
 *   1. Reads the upstream `.claude-plugin/plugin.json` for name/description.
 *   2. Reads `skills/caveman/SKILL.md` — caveman's single source of truth for
 *      the terse-mode ruleset — and strips its YAML frontmatter.
 *   3. Writes a Vellum `package.json` (correct `name`, `@vellumai/plugin-api`
 *      peer dependency).
 *   4. Synthesizes `hooks/pre-model-call.ts`, which appends the ruleset to the
 *      system prompt of the user-facing model call so terse mode is always on.
 *
 * Runs with the staged install directory as its working directory. Any missing
 * input throws, which fails the install (the installer rolls back staging)
 * rather than materializing a half-translated, non-functional plugin.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const PLUGIN_NAME = "caveman";
const PLUGIN_API_RANGE = ">=0.8.0";
const root = process.cwd();

/** Read a required upstream file, failing the install if it is absent. */
function readRequired(relPath) {
  try {
    return readFileSync(join(root, relPath), "utf8");
  } catch (err) {
    throw new Error(
      `caveman adapter: expected upstream file ${relPath} not found ` +
        `(${err instanceof Error ? err.message : String(err)}). The plugin ` +
        `layout may have changed; the adapter needs updating.`,
    );
  }
}

/** Strip a leading YAML frontmatter block (`---` … `---`) from markdown. */
function stripFrontmatter(markdown) {
  const match = /^---\r?\n[\s\S]*?\r?\n---\r?\n?/.exec(markdown);
  return (match ? markdown.slice(match[0].length) : markdown).trim();
}

const manifest = JSON.parse(readRequired(".claude-plugin/plugin.json"));
const ruleset = stripFrontmatter(readRequired("skills/caveman/SKILL.md"));
if (ruleset.length === 0) {
  throw new Error("caveman adapter: SKILL.md ruleset is empty after parsing.");
}

const description =
  typeof manifest.description === "string" && manifest.description.trim()
    ? manifest.description.trim()
    : "Ultra-compressed communication mode.";

const pkg = {
  name: PLUGIN_NAME,
  version: "0.0.0",
  description,
  private: true,
  license: "MIT",
  type: "module",
  peerDependencies: {
    "@vellumai/plugin-api": PLUGIN_API_RANGE,
  },
};
writeFileSync(
  join(root, "package.json"),
  `${JSON.stringify(pkg, null, 2)}\n`,
  "utf8",
);

// `JSON.stringify` yields a valid TypeScript string literal, so the ruleset —
// arbitrary markdown with backticks and `${...}` — embeds safely without
// hand-escaping.
const hook = `/**
 * Auto-generated by the caveman postinstall adapter — do not edit by hand.
 *
 * Appends caveman's terse-mode ruleset (sourced verbatim from the upstream
 * \`skills/caveman/SKILL.md\`) to the system prompt of the user-facing model
 * call, so the assistant communicates in caveman mode on every turn.
 */

import type { PreModelCallContext } from "@vellumai/plugin-api";

const MARKER = "<!-- caveman:terse-mode -->";

const RULESET = ${JSON.stringify(ruleset)};

export default function preModelCall(ctx: PreModelCallContext): void {
  // Only shape the user-facing reply; leave background/utility calls untouched.
  if (ctx.callSite !== "mainAgent") return;
  if (ctx.systemPrompt === undefined) return;
  // Idempotent: the hook fires once per model call within a turn, so guard
  // against appending the ruleset more than once.
  if (ctx.systemPrompt.includes(MARKER)) return;
  ctx.systemPrompt = \`\${ctx.systemPrompt}\\n\\n\${MARKER}\\n\${RULESET}\`;
}
`;
mkdirSync(join(root, "hooks"), { recursive: true });
writeFileSync(join(root, "hooks", "pre-model-call.ts"), hook, "utf8");
